import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const routePath=new URL("../app/api/daily-portal/[token]/attendance/route.ts",import.meta.url);
const pagePath=new URL("../components/daily/DailyAttendanceWorkspace.tsx",import.meta.url);
const portalPath=new URL("../app/daily/portail/[role]/[token]/page.tsx",import.meta.url);
const attendanceApiPath=new URL("../app/api/daily-attendance/[token]/route.ts",import.meta.url);
const organisationAttendancePath=new URL("../app/api/client/daily/attendance/route.ts",import.meta.url);
const followupPath=new URL("../app/api/daily-portal/[token]/followup/route.ts",import.meta.url);
const[route,page,portal,attendanceApi,organisationAttendance,followup]=await Promise.all([readFile(routePath,"utf8"),readFile(pagePath,"utf8"),readFile(portalPath,"utf8"),readFile(attendanceApiPath,"utf8"),readFile(organisationAttendancePath,"utf8"),readFile(followupPath,"utf8")]);
test("le suivi relit les tables canoniques d'émargement",()=>{assert.match(route,/daily_attendance_slots/);assert.match(route,/daily_attendance_records/);assert.doesNotMatch(route,/insert\(/)});
test("le formateur voit toutes les inscriptions actives et l'apprenant seulement la sienne",()=>{assert.match(route,/portal_type==="trainer"/);assert.match(route,/entity_email/);assert.match(route,/declined/);assert.match(route,/cancelled/);assert.match(route,/abandoned/)});
test("les états de présence distinguent absence, justification et émargement manquant",()=>{assert.match(page,/Présent/);assert.match(page,/Absence justifiée/);assert.match(page,/Absence confirmée/);assert.match(page,/Émargement manquant/);assert.match(page,/À émarger/)});
test("la preuve détaillée reste côté serveur",()=>{assert.doesNotMatch(route,/signature_storage_path/);assert.doesNotMatch(route,/ip_address/);assert.doesNotMatch(route,/user_agent/)});
test("les espaces formateur et apprenant donnent accès au suivi",()=>{assert.match(portal,/Présences & émargement/);assert.match(portal,/trainer/);assert.match(portal,/learner/)});
test("la signature apprenant continue d'écrire dans la source canonique",()=>{assert.match(attendanceApi,/daily_attendance_records/);assert.match(attendanceApi,/status:\s*"present"/);assert.match(attendanceApi,/signed_at/)});
test("l'OF qualifie absence ou justification dans le registre canonique",()=>{assert.match(organisationAttendance,/action === "set_absence"/);assert.match(organisationAttendance,/\["absent", "excused", "pending"\]/);assert.match(organisationAttendance,/daily_attendance_records/)});
test("le formateur peut signaler retard absence ou suspicion d'abandon depuis le créneau",()=>{assert.match(page,/report\("delay"/);assert.match(page,/report\("absence"/);assert.match(page,/report\("abandonment_alert"/);assert.match(page,/role==="trainer"/)});
test("les signalements de présence rejoignent la fiche de suivi canonique",()=>{assert.match(followup,/"absence", "delay", "abandonment_alert"/);assert.match(followup,/daily_session_followup_entries/);assert.match(followup,/enrolment_id/)});
test("un signalement est borné à une inscription active de la même session et organisation",()=>{assert.match(followup,/daily_session_enrolments/);assert.match(followup,/\.eq\("session_id", auth\.access\.session_id\)/);assert.match(followup,/\.eq\("organisation_id", auth\.session\.organisation_id\)/);assert.match(followup,/INACTIVE_ENROLMENTS/)});
test("une suspicion d'abandon ne modifie jamais automatiquement l'inscription",()=>{assert.match(followup,/abandonment_alert/);assert.doesNotMatch(followup,/from\("daily_session_enrolments"\)\.update/);assert.match(page,/n'est jamais transformé automatiquement en abandon/)});
