import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const route=fs.readFileSync("app/api/client/daily/registration-requests/route.ts","utf8");
const page=fs.readFileSync("app/client/daily/candidatures/page.tsx","utf8");
const migration=fs.readFileSync("supabase/migrations/20260922152000_a8_agent_analysis_of_decision.sql","utf8");
const materialization=fs.readFileSync("supabase/migrations/20260910183336_daily_registration_request_materialization.sql","utf8");
test("A8 réserve la décision finale à l OF après analyse Selen",()=>{assert.match(migration,/decision_status <> 'ready_for_of'/);assert.match(migration,/agent_analysis_completed_at is null/);assert.match(migration,/p_actor_type <> 'organisation'/);assert.match(route,/Seul le responsable de l’organisme peut prendre la décision finale/);assert.doesNotMatch(page,/Un seul accord OF ou formateur suffit/);});
test("A8 accepte ou refuse définitivement",()=>{assert.match(migration,/decision_status=p_decision/);assert.match(migration,/refused_at/);assert.match(page,/Refuser la candidature/);assert.match(page,/décision finale est enregistrée/);});
test("A8 ne matérialise qu après acceptation OF",()=>{assert.match(materialization,/decision_status <> 'accepted'/);assert.match(route,/requestRow\.decision_status !== "accepted"/);assert.match(page,/Créer l'inscription dans cette session/);});
test("A8 expose la synthèse Selen et masque les dossiers encore en analyse",()=>{assert.match(route,/agent_analysis_summary/);assert.match(page,/waitingAnalysis/);assert.match(page,/Synthèse Selen/);assert.match(page,/ready_for_of/);});
