import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const route=await readFile(new URL("../app/api/client/daily/procedures/route.ts",import.meta.url),"utf8");
const page=await readFile(new URL("../app/client/daily/procedures/page.tsx",import.meta.url),"utf8");
const migration=await readFile(new URL("../supabase/migrations/20260830123100_create_daily_internal_procedures.sql",import.meta.url),"utf8");
const extensionMigration=await readFile(new URL("../supabase/migrations/20260907103500_extend_daily_internal_procedures_difficulties_hazards.sql",import.meta.url),"utf8");
const backfillMigration=await readFile(new URL("../supabase/migrations/20260907190000_backfill_daily_difficulties_hazards.sql",import.meta.url),"utf8");
const privileges=await readFile(new URL("../supabase/migrations/20260830123132_restrict_daily_internal_procedure_privileges.sql",import.meta.url),"utf8");
const layout=await readFile(new URL("../app/client/daily/layout.tsx",import.meta.url),"utf8");

test("les quatre procédures du cahier des charges sont initialisées",()=>{for(const type of["learner_administration","stakeholder_satisfaction","absence_dropout"]){assert.match(route,new RegExp(type));assert.match(migration,new RegExp(type))}assert.match(route,/difficulties_hazards/);assert.match(extensionMigration,/difficulties_hazards/)});
test("la procédure difficultés et aléas conserve une base serveur utile",()=>{for(const recurrentCase of[/Absence ou retard d'un apprenant/,/Risque de décrochage ou d'abandon/,/Absence ou indisponibilité du formateur/,/Prérequis insuffisants ou difficulté pédagogique/,/Besoin d'accessibilité ou situation de handicap non anticipée/,/Incident technique, matériel ou connexion en distanciel/,/Accident, problème de santé ou situation de sécurité/,/Conflit, comportement inadapté, violence, harcèlement ou discrimination/,/Insatisfaction ou réclamation/])assert.match(route,recurrentCase);assert.match(route,/ignoreDuplicates: true/)});
test("les organismes déjà initialisés reçoivent aussi la quatrième procédure",()=>{assert.match(backfillMigration,/insert into public\.daily_internal_procedures/);assert.match(backfillMigration,/procedure_type = 'difficulties_hazards'/);assert.match(backfillMigration,/on conflict \(organisation_id, procedure_type\) do nothing/);assert.doesNotMatch(backfillMigration,/delete\s+from/i)});
test("les écritures restent bornées à l'espace organisme",()=>{assert.match(route,/getDailyClientWorkspace\(\)/);assert.match(route,/capabilities\.legal_profile/);assert.match(migration,/revoke all on table public\.daily_internal_procedures from anon, authenticated/);assert.match(privileges,/grant select, insert, update on table public\.daily_internal_procedures to service_role/);assert.doesNotMatch(privileges,/grant delete/)});
test("le serveur refuse toujours une procédure sans déroulement",()=>{assert.match(page,/name="steps"/);assert.match(route,/const steps = String\(body\.steps \?\? ""\)\.trim\(\)/);assert.match(route,/if \(!steps\)/);assert.match(route,/Le déroulement de la procédure est requis\./)});
test("les procédures sont préremplies, repliées et téléchargeables sans ouverture",()=>{assert.match(page,/const\[open,setOpen\]=useState<string\|null>\(null\)/);assert.match(page,/Télécharger en Word/);assert.match(page,/text-align:justify/);assert.match(page,/Cette déclaration ne vaut pas agrément de l'État/);assert.match(page,/parcours administratif/i);assert.match(page,/parties prenantes/i);assert.match(page,/absences, ruptures de parcours et abandons/i);assert.match(page,/difficultés et aléas/i)});
test("l'accès reste contextuel depuis le suivi qualité",()=>{assert.match(layout,/href: "\/client\/daily\/procedures"/);assert.match(layout,/label: "Procédures internes"/);assert.doesNotMatch(layout,/<nav/)});
