import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const helper=await readFile(new URL("../lib/server/dailySignatureFollowupReminders.ts",import.meta.url),"utf8");
const automation=await readFile(new URL("../app/api/internal/daily/signature-followup-automation/route.ts",import.meta.url),"utf8");
const signature=await readFile(new URL("../app/api/daily-signature/[token]/route.ts",import.meta.url),"utf8");
test("J+3 et J+6 sont des relances email automatiques",()=>{assert.match(helper,/automatic_email_j3/);assert.match(helper,/automatic_email_j6/);assert.match(automation,/sendDailySignatureFollowup/);assert.match(automation,/automaticEmailsSent\+\+/);});
test("J+9 devient une tâche agent d appel",()=>{assert.match(helper,/J9_MS = 9 \* 24/);assert.match(helper,/phone_call_j9/);assert.match(helper,/Appel téléphonique agent J\+9/);});
test("si le début arrive avant la prochaine échéance la séquence escalade vers un agent",()=>{assert.match(helper,/agent_urgent_before_start/);assert.match(helper,/Signature urgente avant début de formation/);assert.match(automation,/startMs<=dueMs/);assert.match(automation,/escalateDailySignatureReminderBeforeStart/);});
test("la signature clôt toute la séquence",()=>{assert.match(signature,/resolveDailySignatureFollowupReminder/);assert.match(helper,/status: "resolved"/);});
