import { NextResponse } from "next/server";
import { getAdminSupabase } from "@/lib/server/clientNdaAccess";

type Params={params:Promise<{token:string}>};
type Json=Record<string,unknown>;
type Question={id:string;type:string;label:string;options:string[];required:boolean;help_text:string;order:number};
const text=(value:unknown)=>String(value??"").trim();
const email=(value:unknown)=>text(value).toLowerCase();
function question(value:unknown,index:number):Question|null{if(!value||typeof value!=="object")return null;const row=value as Json,label=text(row.label),type=text(row.type)||"free_text";if(!label)return null;return{id:text(row.id)||`q_${index+1}`,type,label,options:Array.isArray(row.options)?row.options.map(text).filter(Boolean):[],required:row.required!==false,help_text:text(row.help_text),order:Number.isFinite(Number(row.order))?Number(row.order):index+1}}
function questions(value:unknown){return Array.isArray(value)?value.map(question).filter((q):q is Question=>Boolean(q)).sort((a,b)=>a.order-b.order):[]}
function answer(value:unknown){if(Array.isArray(value))return[...new Set(value.map(text).filter(Boolean))];return text(value)}
async function resolve(token:string){const admin=getAdminSupabase();const{data:access,error:accessError}=await admin.from("daily_portal_access_tokens").select("id,session_id,portal_type,entity_email,status,expires_at").eq("token",token).maybeSingle();if(accessError)throw accessError;if(!access)return{error:"Portail introuvable.",status:404}as const;if(access.portal_type!=="learner")return{error:"Positionnement réservé à l’apprenant.",status:403}as const;if(["revoked","expired"].includes(String(access.status??"")))return{error:"Cet accès n’est plus actif.",status:403}as const;if(access.expires_at&&new Date(access.expires_at).getTime()<Date.now())return{error:"Ce lien de portail a expiré.",status:410}as const;const{data:session,error:sessionError}=await admin.from("daily_sessions").select("id,organisation_id,formation_id,start_date,status,daily_formations(id,title,positioning_mode,positioning_questions)").eq("id",access.session_id).neq("status","archived").maybeSingle();if(sessionError)throw sessionError;if(!session)return{error:"Session introuvable.",status:404}as const;const{data:enrolments,error:enrolmentError}=await admin.from("daily_session_enrolments").select("id,learner_id,status,positioning_status,daily_learners(id,email,first_name,last_name)").eq("session_id",session.id).eq("organisation_id",session.organisation_id).not("status","in","(declined,cancelled,abandoned)");if(enrolmentError)throw enrolmentError;const learnerEmail=email(access.entity_email);const enrolment=(enrolments??[]).find(row=>{const learner=Array.isArray(row.daily_learners)?row.daily_learners[0]:row.daily_learners;return email(learner&&typeof learner==="object"?(learner as Json).email:"")===learnerEmail});if(!enrolment)return{error:"Inscription apprenant introuvable.",status:404}as const;const formation=Array.isArray(session.daily_formations)?session.daily_formations[0]:session.daily_formations;if(!formation||typeof formation!=="object")return{error:"Formation introuvable.",status:404}as const;const{data:response,error:responseError}=await admin.from("daily_positioning_responses").select("id,answers,submitted_at").eq("enrolment_id",enrolment.id).maybeSingle();if(responseError)throw responseError;return{admin,session,enrolment,formation:formation as Json,response}as const}
export async function GET(_request:Request,{params}:Params){const{token}=await params;const clean=text(token);if(!clean)return NextResponse.json({error:"Lien invalide."},{status:400});try{const resolved=await resolve(clean);if("error"in resolved)return NextResponse.json({error:resolved.error},{status:resolved.status});const mode=text(resolved.formation.positioning_mode),items=mode==="selen"?questions(resolved.formation.positioning_questions):[];return NextResponse.json({positioning:{mode,title:text(resolved.formation.title),submitted:Boolean(resolved.response),submittedAt:resolved.response?.submitted_at??null,status:resolved.enrolment.positioning_status,questions:resolved.response?[]:items}})}catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"Positionnement indisponible."},{status:500})}}
export async function POST(request:Request,{params}:Params){const{token}=await params;const clean=text(token);if(!clean)return NextResponse.json({error:"Lien invalide."},{status:400});try{const resolved=await resolve(clean);if("error"in resolved)return NextResponse.json({error:resolved.error},{status:resolved.status});if(resolved.response)return NextResponse.json({error:"Ce positionnement a déjà été transmis."},{status:409});if(text(resolved.formation.positioning_mode)!=="selen")return NextResponse.json({error:"Cette formation utilise un positionnement externe."},{status:409});const items=questions(resolved.formation.positioning_questions);if(!items.length)return NextResponse.json({error:"Questionnaire de positionnement non configuré."},{status:409});const body=await request.json().catch(()=>({}))as Json;const raw=body.answers&&typeof body.answers==="object"&&!Array.isArray(body.answers)?body.answers as Json:{};const answers:Record<string,string|string[]>={};for(const item of items){const value=answer(raw[item.id]);const empty=Array.isArray(value)?value.length===0:!value;if(item.required&&empty)return NextResponse.json({error:`Réponse requise : ${item.label}`},{status:400});if(item.options.length){const selected=Array.isArray(value)?value:value?[value]:[];if(selected.some(v=>!item.options.includes(v)))return NextResponse.json({error:`Réponse invalide : ${item.label}`},{status:400})}answers[item.id]=value}const{data:created,error:insertError}=await resolved.admin.from("daily_positioning_responses").insert({organisation_id:resolved.session.organisation_id,session_id:resolved.session.id,enrolment_id:resolved.enrolment.id,formation_id:resolved.session.formation_id,question_snapshot:items,answers}).select("id,submitted_at").single();if(insertError||!created){if(insertError?.code==="23505")return NextResponse.json({error:"Ce positionnement a déjà été transmis."},{status:409});return NextResponse.json({error:insertError?.message??"Transmission impossible."},{status:500})}return NextResponse.json({submitted:true,submittedAt:created.submitted_at,status:"completed"})}catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"Transmission impossible."},{status:500})}}
