"use client";

import { useEffect, useState } from "react";
import { assistanceFetch } from "@/components/AgentAssistanceBanner";

type Session={id:string;internal_reference?:string|null;end_date?:string|null;daily_formations?:{title?:string}|{title?:string}[]|null};
type Doc={id:string;document_type:string;status:string;version:number;logical_name:string;metadata?:Record<string,unknown>|null;created_at:string};
const labels:Record<string,string>={attendance_summary:"Relevé des présences",completion_certificate:"Certificat de réalisation"};
const sendableStatuses=new Set(["validated","published","active"]);
function title(s:Session){const f=Array.isArray(s.daily_formations)?s.daily_formations[0]:s.daily_formations;return f?.title??s.internal_reference??"Session Daily";}

export default function PosttrainingDocumentsPage(){
 const [sessions,setSessions]=useState<Session[]>([]),[sessionId,setSessionId]=useState(""),[documents,setDocuments]=useState<Doc[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[sendingId,setSendingId]=useState<string|null>(null);
 useEffect(()=>{void(async()=>{const r=await assistanceFetch("/api/client/daily/end-evaluations",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error??"Chargement impossible.");setSessions(d.sessions??[]);setSessionId(d.sessions?.[0]?.id??"");})();},[]);
 async function load(id:string){if(!id)return setDocuments([]);const r=await assistanceFetch(`/api/client/daily/posttraining-documents?session_id=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error??"Chargement impossible.");setDocuments(d.documents??[]);}
 useEffect(()=>{void load(sessionId);},[sessionId]);
 async function generate(){setBusy(true);setError("");setMessage("");const r=await assistanceFetch("/api/client/daily/posttraining-documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId})});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setError(d.error??"Génération impossible.");setMessage(`${d.count??0} document(s) de fin généré(s), dont ${d.eligibleCertificates??0} certificat(s) de réalisation.`);await load(sessionId);}
 async function sendCertificate(document:Doc){setSendingId(document.id);setError("");setMessage("");try{const r=await assistanceFetch("/api/client/daily/posttraining-documents/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({document_id:document.id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Envoi impossible.");const proof=d.evidenceRecorded===false?" L’e-mail est parti, mais la preuve technique doit être contrôlée par Selen.":" La version exacte envoyée est conservée dans Communications.";setMessage(`Certificat envoyé à ${d.sentTo}.${proof}`);}catch(cause){setError(cause instanceof Error?cause.message:"Envoi impossible.");}finally{setSendingId(null);}}
 return <main style={{maxWidth:1100,margin:"0 auto",padding:"2rem 1rem 4rem",color:"#3f2b1d"}}><p style={{fontWeight:800,color:"#8a4b24"}}>Selen Daily · Après la formation</p><h1>Documents de fin</h1><p>Génère le relevé des présences et les certificats de réalisation à partir des émargements réellement enregistrés. Un certificat n’est produit que lorsque les présences de l’apprenant sont entièrement renseignées et qu’au moins une présence est constatée. Après validation Selen, il peut être envoyé directement à l’apprenant avec conservation de la preuve.</p>{error?<p style={{padding:12,border:"1px solid #8a4b24"}}>{error}</p>:null}{message?<p style={{padding:12,border:"1px solid #6a8a4a"}}>{message}</p>:null}<section style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end",padding:16,border:"1px solid #d8b989",background:"#fffaf0"}}><label style={{display:"grid",gap:5,minWidth:280}}>Session<select value={sessionId} onChange={e=>setSessionId(e.target.value)} style={{padding:10}}><option value="">Choisir une session</option>{sessions.map(s=><option key={s.id} value={s.id}>{title(s)}</option>)}</select></label>{sessionId?<button type="button" disabled={busy||Boolean(sendingId)} onClick={()=>void generate()} style={{padding:"10px 14px",fontWeight:800}}>{busy?"Génération...":"Générer / régénérer"}</button>:null}</section><section style={{display:"grid",gap:10,marginTop:16}}>{documents.length===0&&sessionId?<p>Aucun document de fin généré pour cette session.</p>:documents.map(doc=>{const canSend=doc.document_type==="completion_certificate"&&sendableStatuses.has(doc.status);return <article key={doc.id} style={{padding:14,border:"1px solid #d8b989",background:"#fffaf0",display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{labels[doc.document_type]??doc.document_type}</strong>{typeof doc.metadata?.learner_name==="string"?` · ${doc.metadata.learner_name}`:""}<div style={{fontSize:12,marginTop:4}}>v{doc.version} · {doc.status}</div>{doc.document_type==="completion_certificate"&&!canSend?<div style={{fontSize:12,marginTop:5,color:"#6d5a4a"}}>Envoi disponible après validation par Selen.</div>:null}</div><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><a href={`/api/client/daily/posttraining-documents/download?id=${encodeURIComponent(doc.id)}`} target="_blank" rel="noreferrer">Télécharger</a>{canSend?<button type="button" disabled={Boolean(sendingId)||busy} onClick={()=>void sendCertificate(doc)} style={{padding:"8px 11px",fontWeight:800}}>{sendingId===doc.id?"Envoi…":"Envoyer à l’apprenant"}</button>:null}</div></article>;})}</section></main>;
}
