"use client";

import { FormEvent, useEffect, useState } from "react";
import LoadingMascot from "@/components/ui/LoadingMascot";

type Procedure = {
  id: string;
  procedure_type: "learner_administration" | "stakeholder_satisfaction" | "absence_dropout" | "difficulties_hazards";
  title: string;
  purpose: string | null;
  steps: string;
  responsibilities: string | null;
  evidence: string | null;
  status: "draft" | "active";
  reviewed_at: string | null;
  updated_at: string;
};

const prompts: Record<Procedure["procedure_type"], { purpose: string; steps: string; responsibilities: string; evidence: string }> = {
  learner_administration: { purpose: "Adaptez le périmètre de votre parcours administratif à votre organisation, de l’inscription jusqu’à l’archivage du dossier.", steps: "Modifiez les étapes proposées pour refléter votre fonctionnement réel.", responsibilities: "Précisez qui réalise ou contrôle chaque étape dans votre organisme.", evidence: "Indiquez les traces réellement conservées : emails, signatures, dossiers de session…" },
  stakeholder_satisfaction: { purpose: "Adaptez les parties prenantes interrogées et la façon dont vous exploitez leurs retours.", steps: "Précisez vos envois, relances, analyses et décisions d'amélioration.", responsibilities: "Précisez qui suit les réponses et les éventuelles actions.", evidence: "Indiquez les questionnaires, synthèses, relances et décisions conservées." },
  absence_dropout: { purpose: "Adaptez votre dispositif de prévention et de traitement des absences, ruptures de parcours et abandons.", steps: "Décrivez vos délais de prise de contact, solutions possibles et règles de clôture.", responsibilities: "Précisez qui alerte, qui contacte et qui arbitre les adaptations.", evidence: "Indiquez les traces conservées : présences, échanges, adaptations, décisions." },
  difficulties_hazards: { purpose: "Adaptez le périmètre aux difficultés et aléas réellement susceptibles d’affecter vos formations.", steps: "Modifiez-la, supprimez les cas inutiles et ajoutez ceux propres à votre activité. Selen propose une base de situations récurrentes à personnaliser.", responsibilities: "Précisez qui détecte, traite et arbitre chaque situation.", evidence: "Indiquez les traces pertinentes selon l’événement : suivi, adaptation, incident, réclamation ou action corrective." },
};

function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function downloadProcedure(procedure:Procedure, form:HTMLFormElement|null){if(!form)return;const data=new FormData(form);const body=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Georgia,serif;margin:45px;color:#33271f;line-height:1.55}h1{color:#7a2e22;border-bottom:2px solid #b28a62;padding-bottom:12px}h2{margin-top:28px;color:#5c3a1e}.block{white-space:pre-wrap}.foot{margin-top:45px;border-top:1px solid #b28a62;padding-top:10px;color:#78634f;font-size:10pt}</style></head><body><h1>${escapeHtml(procedure.title)}</h1><h2>Objectif et périmètre</h2><div class="block">${escapeHtml(String(data.get("purpose")??""))}</div><h2>Déroulement</h2><div class="block">${escapeHtml(String(data.get("steps")??""))}</div><h2>Rôles et responsabilités</h2><div class="block">${escapeHtml(String(data.get("responsibilities")??""))}</div><h2>Traces et preuves conservées</h2><div class="block">${escapeHtml(String(data.get("evidence")??""))}</div><div class="foot">Modèle personnalisé depuis Selen Daily · ${new Intl.DateTimeFormat("fr-FR").format(new Date())}</div></body></html>`;const url=URL.createObjectURL(new Blob([body],{type:"application/msword"}));const a=document.createElement("a");a.href=url;a.download=`Procedure_${procedure.procedure_type}.doc`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

export default function DailyProceduresPage() {
  const [procedures,setProcedures]=useState<Procedure[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/client/daily/procedures",{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??"Procédures indisponibles.");setProcedures((body.procedures??[]) as Procedure[])}catch(cause){setError(cause instanceof Error?cause.message:"Chargement impossible.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function save(event:FormEvent<HTMLFormElement>,procedure:Procedure){event.preventDefault();const form=new FormData(event.currentTarget);setSaving(procedure.procedure_type);setError("");setMessage("");const response=await fetch("/api/client/daily/procedures",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({procedureType:procedure.procedure_type,purpose:form.get("purpose"),steps:form.get("steps"),responsibilities:form.get("responsibilities"),evidence:form.get("evidence"),status:form.get("status")})});const body=await response.json().catch(()=>({}));setSaving("");if(!response.ok){setError(body.error??"Enregistrement impossible.");return}setProcedures(current=>current.map(item=>item.procedure_type===procedure.procedure_type?body.procedure:item));setMessage("Votre procédure a bien été enregistrée.")}
  if(loading)return <LoadingMascot message="Sélion rassemble vos procédures…"/>;
  return <main style={s.page}><div style={s.wrap}><header style={s.card}><p style={s.kicker}>Selen Daily · Qualité</p><h1 style={s.h1}>Procédures internes</h1><p style={s.muted}>Vous disposez de modèles déjà structurés et personnalisables pour formaliser vos propres méthodes, sans exposer ses propres méthodes internes à Selen. Modifiez-les selon votre fonctionnement réel, enregistrez votre version puis téléchargez-la en Word pour l'utiliser ou l'archiver.</p></header>{error?<p style={s.error}>{error}</p>:null}{message?<p style={s.ok}>{message}</p>:null}{procedures.map(procedure=>{const guidance=prompts[procedure.procedure_type];return <form key={procedure.id} onSubmit={event=>void save(event,procedure)} style={s.card}><div style={s.head}><div><p style={s.kicker}>Modèle de procédure</p><h2 style={s.h2}>{procedure.title}</h2></div><span style={procedure.status==="active"?s.badgeOk:s.badgeDraft}>{procedure.status==="active"?"Active":"Brouillon"}</span></div><Field name="purpose" label="Objectif et périmètre" initial={procedure.purpose??""} help={guidance.purpose}/><Field name="steps" label="Déroulement de la procédure" initial={procedure.steps} help={guidance.steps} rows={9} required/><Field name="responsibilities" label="Rôles et responsabilités" initial={procedure.responsibilities??""} help={guidance.responsibilities}/><Field name="evidence" label="Traces et preuves conservées" initial={procedure.evidence??""} help={guidance.evidence}/><div style={s.actions}><label style={s.label}>État<select name="status" defaultValue={procedure.status} style={s.input}><option value="draft">Brouillon</option><option value="active">Active</option></select></label><div style={s.buttons}><button type="button" onClick={event=>downloadProcedure(procedure,event.currentTarget.closest("form"))} style={s.secondary}>Télécharger en Word</button><button type="submit" disabled={saving===procedure.procedure_type} style={s.button}>{saving===procedure.procedure_type?"Enregistrement…":"Enregistrer"}</button></div></div></form>})}</div></main>
}
function Field({name,label,initial,help,rows=4,required=false}:{name:string;label:string;initial:string;help:string;rows?:number;required?:boolean}){return <label style={s.label}>{label}<textarea name={name} defaultValue={initial} rows={rows} required={required} style={s.input}/><small style={s.help}>{help}</small></label>}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",padding:"2rem 1rem 5rem",color:"#392a19"},wrap:{maxWidth:1040,margin:"auto",display:"grid",gap:16},card:{background:"rgba(248,240,220,.9)",border:"1px solid #d9c391",padding:"1.5rem",boxShadow:"0 8px 20px rgba(57,42,25,.08)",display:"grid",gap:14},kicker:{textTransform:"uppercase",letterSpacing:".14em",fontSize:11,fontWeight:800,color:"#9b682d",margin:0},h1:{fontSize:"clamp(2rem,5vw,3rem)",margin:".3rem 0"},h2:{margin:".25rem 0 0"},muted:{color:"#725e46",lineHeight:1.6},head:{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"start"},label:{display:"grid",gap:6,fontWeight:800},input:{width:"100%",boxSizing:"border-box",border:"1px solid #cdb785",background:"#fffaf0",padding:10,color:"#392a19",font:"inherit"},help:{color:"#725e46",fontWeight:400,lineHeight:1.45},actions:{display:"flex",justifyContent:"space-between",gap:12,alignItems:"end",flexWrap:"wrap",borderTop:"1px solid #d9c391",paddingTop:12},buttons:{display:"flex",gap:8,flexWrap:"wrap"},button:{border:"1px solid #7a2e22",background:"#7a2e22",color:"#fff8e8",padding:".62rem .82rem",fontWeight:800,cursor:"pointer"},secondary:{border:"1px solid #b89b6c",background:"transparent",padding:".62rem .82rem",fontWeight:700,color:"#5c3a1e",cursor:"pointer"},badgeOk:{padding:".4rem .65rem",border:"1px solid #668153",color:"#455a3b"},badgeDraft:{padding:".4rem .65rem",border:"1px solid #b5792d",color:"#7b4e19"},ok:{border:"1px solid #668153",padding:10,color:"#455a3b",background:"#f3f8ef"},error:{border:"1px solid #a64b3b",padding:10,color:"#7d2e22",background:"#fff2ee"}};
