import { NextResponse } from "next/server";
import { getDailyClientWorkspace } from "@/lib/server/dailyClientWorkspace";
import { getAdminSupabase } from "@/lib/server/clientNdaAccess";

function clean(value:unknown){return String(value??"").trim()}
function cleanArray(value:unknown){return Array.isArray(value)?[...new Set(value.map(clean).filter(Boolean))]:[]}
async function ownTrainer(){const context=await getDailyClientWorkspace();if(!context.ok)return context;if(!context.workspace.capabilities.trainer_self&&!context.workspace.membership.roles.includes("trainer"))return{ok:false as const,status:403,error:"Accès réservé au formateur concerné."};const profile=context.workspace.trainers.find(t=>String(t.user_id??"")===context.user.id)??context.workspace.trainers[0];if(!profile?.id)return{ok:false as const,status:404,error:"Fiche formateur introuvable."};return{...context,profile,admin:getAdminSupabase(),organisationId:context.workspace.membership.organisation_id}}
export async function GET(){const context=await ownTrainer();if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});const{data,error}=await context.admin.from("daily_trainer_profiles").select("id,display_name,professional_email,phone,engagement_type,biography,specialties,status,cv_updated_at,cv_review_due_at").eq("id",context.profile.id).eq("organisation_id",context.organisationId).maybeSingle();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({profile:data,annual_review_exempt:data?.engagement_type==="owner"})}
export async function PATCH(req:Request){const context=await ownTrainer();if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});const body=await req.json().catch(()=>({}));const updates={biography:clean(body.biography)||null,specialties:cleanArray(body.specialties),professional_email:clean(body.professional_email).toLowerCase()||null,phone:clean(body.phone)||null,updated_at:new Date().toISOString()};const{data,error}=await context.admin.from("daily_trainer_profiles").update(updates).eq("id",context.profile.id).eq("organisation_id",context.organisationId).select("id,display_name,professional_email,phone,engagement_type,biography,specialties,status,cv_updated_at,cv_review_due_at").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({profile:data,annual_review_exempt:data.engagement_type==="owner"})}
