import {NextResponse} from "next/server";
import {getAdminSupabase} from "@/lib/server/clientNdaAccess";
import {DAILY_PORTAL_RESOURCE_STATUSES,DAILY_PORTAL_RESOURCE_TYPES,isDailyPortalResourceVisible} from "@/lib/server/dailyPortalResourceVisibility";

type Params={params:Promise<{token:string}>};type JsonRecord=Record<string,unknown>;
const text=(value:unknown)=>String(value??"").trim();const normalizedEmail=(value:unknown)=>text(value).toLowerCase();
function isExpired(value:unknown){const date=text(value);return Boolean(date&&new Date(date).getTime()<Date.now())}
function relatedLearner(value:unknown):JsonRecord|null{return Array.isArray(value)?value[0]&&typeof value[0]==="object"?value[0] as JsonRecord:null:value&&typeof value==="object"?value as JsonRecord:null}
function virtualDocumentTarget(documentId:string){const match=/^portal:(convention|regulations|welcome):(.+)$/.exec(documentId);if(!match)return null;return{route:match[1]==="welcome"?"convocation":"convention",sourceId:match[2]}}

export async function GET(request:Request,{params}:Params){
  const{token}=await params;const clean=text(token),documentId=new URL(request.url).searchParams.get("id")??"";if(!clean||!documentId)return NextResponse.json({error:"Lien invalide."},{status:400});
  const supabase=getAdminSupabase();const{data:access,error:accessError}=await supabase.from("daily_portal_access_tokens").select("id,session_id,portal_type,entity_email,status,expires_at").eq("token",clean).maybeSingle();
  if(accessError)return NextResponse.json({error:accessError.message},{status:500});if(!access||!["learner","trainer","enterprise"].includes(access.portal_type))return NextResponse.json({error:"Document introuvable."},{status:404});if(["revoked","expired"].includes(String(access.status??"")))return NextResponse.json({error:"Cet accès n’est plus actif."},{status:403});if(isExpired(access.expires_at))return NextResponse.json({error:"Ce lien de portail a expiré."},{status:410});
  const{data:session,error:sessionError}=await supabase.from("daily_sessions").select("id,organisation_id,status").eq("id",access.session_id).neq("status","archived").maybeSingle();if(sessionError)return NextResponse.json({error:sessionError.message},{status:500});if(!session)return NextResponse.json({error:"Session introuvable."},{status:404});
  const virtualTarget=virtualDocumentTarget(documentId);if(virtualTarget){if(access.portal_type!=="learner")return NextResponse.json({error:"Document introuvable."},{status:404});const target=new URL(`/api/daily-portal/${encodeURIComponent(clean)}/${virtualTarget.route}`,request.url);target.searchParams.set("id",virtualTarget.sourceId);return NextResponse.redirect(target)}
  const{data:document,error:documentError}=await supabase.from("daily_documents").select("id,organisation_id,document_type,linked_object_type,linked_object_id,session_id,enrolment_id,learner_id,status,is_current,bucket,storage_path,metadata").eq("id",documentId).eq("organisation_id",session.organisation_id).eq("is_current",true).in("status",DAILY_PORTAL_RESOURCE_STATUSES).in("document_type",DAILY_PORTAL_RESOURCE_TYPES).maybeSingle();if(documentError)return NextResponse.json({error:documentError.message},{status:500});if(!document)return NextResponse.json({error:"Document introuvable."},{status:404});
  const enrolmentIds:string[]=[],learnerIds:string[]=[];const entityEmail=normalizedEmail(access.entity_email);if(access.portal_type==="learner"&&entityEmail){const{data:enrolments,error}=await supabase.from("daily_session_enrolments").select("id,learner_id,daily_learners(id,email)").eq("session_id",access.session_id).eq("organisation_id",session.organisation_id).not("status","in","(declined,cancelled,abandoned)");if(error)return NextResponse.json({error:error.message},{status:500});for(const row of enrolments??[]){if(normalizedEmail(relatedLearner(row.daily_learners)?.email)===entityEmail){enrolmentIds.push(String(row.id));learnerIds.push(String(row.learner_id))}}}
  if(!isDailyPortalResourceVisible({resource:document,role:access.portal_type,sessionId:String(access.session_id),enrolmentIds,learnerIds}))return NextResponse.json({error:"Document introuvable."},{status:404});
  const{data:signed,error:signedError}=await supabase.storage.from(document.bucket).createSignedUrl(document.storage_path,120);if(signedError||!signed?.signedUrl)return NextResponse.json({error:"Téléchargement indisponible."},{status:500});return NextResponse.redirect(signed.signedUrl);
}
