import { NextResponse } from "next/server";
import { getAdminSupabase } from "@/lib/server/clientNdaAccess";

type Params={params:Promise<{token:string}>};type JsonRecord=Record<string,unknown>;
const allowedStatuses=["validated","published","signed","active"];
const text=(v:unknown)=>String(v??"").trim();const normalizedEmail=(v:unknown)=>text(v).toLowerCase();
function isExpired(v:unknown){const d=text(v);return Boolean(d&&new Date(d).getTime()<Date.now())}
function relatedLearner(v:unknown):JsonRecord|null{return Array.isArray(v)?v[0]&&typeof v[0]==="object"?v[0] as JsonRecord:null:v&&typeof v==="object"?v as JsonRecord:null}
function metadata(v:unknown):JsonRecord{return v&&typeof v==="object"&&!Array.isArray(v)?v as JsonRecord:{}}

export async function GET(request:Request,{params}:Params){
 const{token}=await params;const clean=text(token),documentId=new URL(request.url).searchParams.get("id")??"";if(!clean||!documentId)return NextResponse.json({error:"Lien invalide."},{status:400});const supabase=getAdminSupabase();const{data:access,error:accessError}=await supabase.from("daily_portal_access_tokens").select("id,session_id,portal_type,entity_email,status,expires_at").eq("token",clean).maybeSingle();if(accessError)return NextResponse.json({error:accessError.message},{status:500});if(!access||access.portal_type!=="learner")return NextResponse.json({error:"Document introuvable."},{status:404});if(isExpired(access.expires_at))return NextResponse.json({error:"Ce lien de portail a expiré."},{status:410});
 const{data:session,error:sessionError}=await supabase.from("daily_sessions").select("id,organisation_id,status").eq("id",access.session_id).neq("status","archived").maybeSingle();if(sessionError)return NextResponse.json({error:sessionError.message},{status:500});if(!session)return NextResponse.json({error:"Session introuvable."},{status:404});
 const{data:document,error:documentError}=await supabase.from("daily_documents").select("id,organisation_id,document_type,linked_object_type,linked_object_id,status,is_current,bucket,storage_path,metadata").eq("id",documentId).eq("organisation_id",session.organisation_id).eq("is_current",true).in("status",allowedStatuses).in("document_type",["training_program","completion_certificate","organisation_shared"]).maybeSingle();if(documentError)return NextResponse.json({error:documentError.message},{status:500});if(!document)return NextResponse.json({error:"Document introuvable."},{status:404});
 const entityEmail=normalizedEmail(access.entity_email);let enrolmentId:string|null=null,learnerId:string|null=null;if(entityEmail){const{data:enrolments,error}=await supabase.from("daily_session_enrolments").select("id,learner_id,daily_learners(id,email)").eq("session_id",access.session_id).eq("organisation_id",session.organisation_id).not("status","in","(declined,cancelled)");if(error)return NextResponse.json({error:error.message},{status:500});const row=(enrolments??[]).find(r=>normalizedEmail(relatedLearner(r.daily_learners)?.email)===entityEmail);enrolmentId=row?.id??null;learnerId=row?.learner_id??null}
 let allowed=document.document_type==="training_program"&&document.linked_object_type==="session"&&document.linked_object_id===access.session_id;if(!allowed&&document.document_type==="completion_certificate")allowed=Boolean(enrolmentId&&document.linked_object_type==="enrolment"&&document.linked_object_id===enrolmentId);if(!allowed&&document.document_type==="organisation_shared"){const m=metadata(document.metadata),scope=String(m.distribution_scope??"");allowed=scope==="organisation"||(scope==="session"&&String(m.session_id??"")===String(access.session_id??""))||(scope==="learners"&&String(m.session_id??"")===String(access.session_id??"")&&Boolean(learnerId)&&Array.isArray(m.learner_ids)&&(m.learner_ids as unknown[]).map(String).includes(String(learnerId)))}if(!allowed)return NextResponse.json({error:"Document introuvable."},{status:404});const{data:signed,error:signedError}=await supabase.storage.from(document.bucket).createSignedUrl(document.storage_path,120);if(signedError||!signed?.signedUrl)return NextResponse.json({error:"Téléchargement indisponible."},{status:500});return NextResponse.redirect(signed.signedUrl)
}
