"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import LoadingMascot from "@/components/ui/LoadingMascot";

type Session={id:string;internal_reference:string|null;start_date:string|null;daily_formations?:{title?:string|null}|{title?:string|null}[]|null};
type Enrolment={id:string;session_id:string;learner_id:string;daily_learners?:{id:string;first_name:string;last_name:string;email:string|null}|{id:string;first_name:string;last_name:string;email:string|null}[]|null};
type SharedDoc={id:string;logical_name:string;created_at:string;metadata:Record<string,unknown>};
function one<T>(v:T|T[]|null|undefined):T|null{return Array.isArray(v)?v[0]??null:v??null}
function label(s:Session){return s.internal_reference||one(s.daily_formations)?.title||"Session"}
export default function LearnerSharedDocumentsPage(){
 const[documents,setDocuments]=useState<SharedDoc[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[enrolments,setEnrolments]=useState<Enrolment[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[scope,setScope]=useState("organisation");const[sessionId,setSessionId]=useState("");const[selected,setSelected]=useState<string[]>([]);
 async function load(){setLoading(true);const r=await fetch("/api/client/daily/learner-shared-documents",{cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok)setError(b.error??"Bibliothèque indisponible.");else{setDocuments(b.documents??[]);setSessions(b.sessions??[]);setEnrolments(b.enrolments??[])}setLoading(false)}
 useEffect(()=>{void load()},[]);const learners=useMemo(()=>enrolments.filter(x=>x.session_id===sessionId),[enrolments,sessionId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");setMessage("");const f=new FormData(e.currentTarget);f.set("scope",scope);f.set("session_id",sessionId);f.set("learner_ids",JSON.stringify(selected));const r=await fetch("/api/client/daily/learner-shared-documents",{method:"POST",body:f});const b=await r.json().catch(()=>({}));if(!r.ok)setError(b.error??"Import impossible.");else{e.currentTarget.reset();setScope("organisation");setSessionId("");setSelected([]);setMessage("Document publié dans les espaces apprenants concernés.");await load()}setSaving(false)}
 async function archive(id:string){const r=await fetch(`/api/client/daily/learner-shared-documents?id=${encodeURIComponent(id)}`,{method:"DELETE"});const b=await r.json().catch(()=>({}));if(!r.ok)setError(b.error??"Archivage impossible.");else await load()}
 if(loading)return <LoadingMascot message="Sélion ouvre la bibliothèque apprenants…"/>;
 return <main style={s.page}><div style={s.wrap}><header style={s.card}><p style={s.kicker}>Selen Daily · Documents de l'organisme</p><h1 style={s.h1}>Documents à diffuser aux apprenants</h1><p style={s.muted}>Ajoutez ici les documents propres à votre organisme. Ils restent distincts des documents générés par Selen.</p></header>{error?<p style={s.error}>{error}</p>:null}{message?<p style={s.ok}>{message}</p>:null}<section style={s.card}><h2>Publier un document</h2><form onSubmit={submit} style={s.form}><label style={s.field}>Titre du document<input name="title" required style={s.input}/></label><label style={s.field}>Fichier<input name="file" type="file" required accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp" style={s.input}/></label><fieldset style={s.fieldset}><legend>Diffusion</legend><label><input type="radio" checked={scope==="organisation"} onChange={()=>{setScope("organisation");setSessionId("");setSelected([])}}/> Tous les espaces apprenants de l'organisme, y compris les futurs</label><label><input type="radio" checked={scope==="session"} onChange={()=>{setScope("session");setSelected([])}}/> Tous les apprenants d'une session</label><label><input type="radio" checked={scope==="learners"} onChange={()=>setScope("learners")}/> Certains apprenants d'une session</label></fieldset>{scope!=="organisation"?<label style={s.field}>Session<select value={sessionId} required onChange={e=>{setSessionId(e.target.value);setSelected([])}} style={s.input}><option value="">Choisir une session</option>{sessions.map(x=><option key={x.id} value={x.id}>{label(x)}{x.start_date?` · ${x.start_date}`:""}</option>)}</select></label>:null}{scope==="learners"&&sessionId?<div style={s.learners}><strong>Apprenants concernés</strong>{learners.length?learners.map(row=>{const l=one(row.daily_learners);return l?<label key={row.learner_id}><input type="checkbox" checked={selected.includes(row.learner_id)} onChange={e=>setSelected(cur=>e.target.checked?[...cur,row.learner_id]:cur.filter(id=>id!==row.learner_id))}/> {l.first_name} {l.last_name}{l.email?` · ${l.email}`:""}</label>:null}):<span>Aucun apprenant actif dans cette session.</span>}</div>:null}<button disabled={saving} style={s.primary}>{saving?"Publication…":"Publier dans les espaces apprenants"}</button></form></section><section style={s.card}><h2>Documents publiés</h2>{documents.length===0?<p style={s.muted}>Aucun document propre à l'organisme n'est diffusé pour le moment.</p>:<div style={s.list}>{documents.map(d=>{const scopeText=d.metadata?.distribution_scope==="organisation"?"Tous les apprenants":d.metadata?.distribution_scope==="session"?"Une session":"Apprenants sélectionnés";return <article key={d.id} style={s.row}><div><strong>{d.logical_name}</strong><p style={s.muted}>{scopeText} · publié le {new Intl.DateTimeFormat("fr-FR").format(new Date(d.created_at))}</p></div><button type="button" onClick={()=>void archive(d.id)} style={s.secondary}>Archiver</button></article>})}</div>}</section></div></main>
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",padding:"2rem 1rem 5rem",background:"linear-gradient(180deg,#eadfbf,#e0cf9f)",color:"#392a19"},wrap:{maxWidth:980,margin:"auto",display:"grid",gap:16},card:{background:"#f8f0dc",border:"1px solid #d9c391",padding:"1.5rem",boxShadow:"0 8px 20px rgba(57,42,25,.08)"},kicker:{textTransform:"uppercase",letterSpacing:".14em",fontSize:11,fontWeight:800,color:"#9b682d"},h1:{fontFamily:"Georgia,serif",fontSize:"clamp(2rem,5vw,3rem)",margin:".3rem 0"},muted:{color:"#725e46",lineHeight:1.55,margin:".3rem 0"},form:{display:"grid",gap:12},field:{display:"grid",gap:5,fontWeight:700},input:{border:"1px solid #cdb785",background:"#fffaf0",padding:10,color:"#392a19"},fieldset:{display:"grid",gap:8,border:"1px solid #d9c391",padding:12},learners:{display:"grid",gap:7,border:"1px solid #d9c391",padding:12,background:"#fffaf0"},primary:{width:"fit-content",border:"1px solid #7a2e22",background:"#7a2e22",color:"#fff8e8",padding:".75rem 1rem",fontWeight:800,cursor:"pointer"},secondary:{border:"1px solid #b89b6c",background:"transparent",padding:".55rem .7rem",fontWeight:700,color:"#5c3a1e",cursor:"pointer"},list:{display:"grid",gap:8},row:{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",border:"1px solid #d9c391",padding:12,background:"#fffaf0"},error:{border:"1px solid #a64b3b",background:"#fff2ee",padding:10,color:"#7d2e22"},ok:{border:"1px solid #668153",background:"#f3f8ef",padding:10,color:"#455a3b"}};
