import { NextResponse } from "next/server";
import { getAdminSupabase } from "@/lib/server/clientNdaAccess";

type Params={params:Promise<{token:string}>};type JsonRecord=Record<string,unknown>;
const learnerDocumentStatuses=["validated","published","signed","active"];
const cleanToken=(v?:string|null)=>String(v??"").trim();const normalizedEmail=(v:unknown)=>String(v??"").trim().toLowerCase();
function fullName(first?:unknown,last?:unknown){return[first,last].map(v=>String(v??"").trim()).filter(Boolean).join(" ")}
function asArray(v:unknown):JsonRecord[]{return Array.isArray(v)?v.filter(x=>x&&typeof x==="object") as JsonRecord[]:[]}
function portalRole(v:string){return v==="learner"?"apprenant":v==="enterprise"?"entreprise":"formateur"}
function isExpired(v?:string|null){return Boolean(v&&new Date(v).getTime()<Date.now())}
function relatedLearner(v:unknown):JsonRecord|null{return Array.isArray(v)?v[0]&&typeof v[0]==="object"?v[0] as JsonRecord:null:v&&typeof v==="object"?v as JsonRecord:null}
function meta(v:unknown):JsonRecord{return v&&typeof v==="object"&&!Array.isArray(v)?v as JsonRecord:{}}

async function loadLearnerDocuments(supabase:ReturnType<typeof getAdminSupabase>,access:JsonRecord,organisationId:string){
 if(access.portal_type!=="learner")return[];const entityEmail=normalizedEmail(access.entity_email);if(!entityEmail)return[];
 const{data:enrolments,error:enrolmentError}=await supabase.from("daily_session_enrolments").select("id,learner_id,status,daily_learners(id,email)").eq("session_id",access.session_id).eq("organisation_id",organisationId).not("status","in","(declined,cancelled)");if(enrolmentError)throw enrolmentError;
 const enrolment=(enrolments??[]).find(row=>normalizedEmail(relatedLearner(row.daily_learners)?.email)===entityEmail);const enrolmentId=enrolment?.id??null,learnerId=enrolment?.learner_id??null;
 const{data:documents,error:documentError}=await supabase.from("daily_documents").select("id,document_type,linked_object_type,linked_object_id,logical_name,version,status,mime_type,created_at,metadata").eq("organisation_id",organisationId).eq("is_current",true).in("status",learnerDocumentStatuses).in("document_type",["training_program","completion_certificate","organisation_shared"]).order("created_at",{ascending:false});if(documentError)throw documentError;
 return(documents??[]).filter(document=>{if(document.document_type==="training_program")return document.linked_object_type==="session"&&document.linked_object_id===access.session_id;if(document.document_type==="completion_certificate")return Boolean(enrolmentId&&document.linked_object_type==="enrolment"&&document.linked_object_id===enrolmentId);const m=meta(document.metadata),scope=String(m.distribution_scope??"");if(scope==="organisation")return true;if(scope==="session")return String(m.session_id??"")===String(access.session_id??"");if(scope==="learners")return String(m.session_id??"")===String(access.session_id??"")&&Boolean(learnerId)&&Array.isArray(m.learner_ids)&&(m.learner_ids as unknown[]).map(String).includes(String(learnerId));return false})
}

export async function GET(_request:Request,{params}:Params){
 const{token}=await params;const clean=cleanToken(token);if(!clean)return NextResponse.json({error:"Lien invalide."},{status:400});const supabase=getAdminSupabase();const{data:access,error:accessError}=await supabase.from("daily_portal_access_tokens").select("*").eq("token",clean).maybeSingle();if(accessError)return NextResponse.json({error:accessError.message},{status:500});if(!access)return NextResponse.json({error:"Portail introuvable."},{status:404});if(isExpired(access.expires_at)){await supabase.from("daily_portal_access_tokens").update({status:"expired"}).eq("id",access.id);return NextResponse.json({error:"Ce lien de portail a expire."},{status:410})}if(access.status==="pending")await supabase.from("daily_portal_access_tokens").update({status:"viewed",viewed_at:new Date().toISOString()}).eq("id",access.id);
 const[sessionR,onboardingR,responsesR,conventionsR,trainersR,convocationsR]=await Promise.all([
  supabase.from("daily_sessions").select("*, daily_formations(id,title,status,global_objective,target_audience,duration_hours,duration_days,modality)").eq("id",access.session_id).neq("status","archived").maybeSingle(),
  supabase.from("daily_onboarding").select("organisation_name,platform_contact_first_name,platform_contact_last_name,platform_contact_email,address").eq("user_id",access.user_id).maybeSingle(),
  supabase.from("daily_registration_responses").select("id,response_type,respondent_first_name,respondent_last_name,respondent_email,company_name,need_answers,positioning_answers,adaptation_needed,submitted_at").eq("session_id",access.session_id),
  supabase.from("daily_conventions").select("id,recipient_type,recipient_key,recipient_name,recipient_email,company_name,version,document_name,generated_at,daily_convention_signatures(id,signatory_type,signatory_name,signatory_email,token,status,signed_at)").eq("session_id",access.session_id),
  supabase.from("daily_trainers").select("id,first_name,last_name,email").eq("user_id",access.user_id),
  supabase.from("daily_convocations").select("id,recipient_type,recipient_key,recipient_name,recipient_email,company_name,version,document_name,status,sent_at,generated_at").eq("session_id",access.session_id),
 ]);if(sessionR.error)return NextResponse.json({error:sessionR.error.message},{status:500});const session=sessionR.data;if(!session)return NextResponse.json({error:"Session introuvable."},{status:404});let learnerDocuments:JsonRecord[]=[];try{learnerDocuments=await loadLearnerDocuments(supabase,access,String(session.organisation_id??"")) as JsonRecord[]}catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"Documents indisponibles."},{status:500})}
 const responseRows=responsesR.data??[],conventionRows=conventionsR.data??[],entityEmail=normalizedEmail(access.entity_email),entityName=String(access.entity_name??"").trim().toLowerCase();const individualLearners=asArray(session.individual_beneficiaries),companyLearners=asArray(session.beneficiaries),companies=asArray(session.companies);const learner=[...individualLearners,...companyLearners].find(p=>{const email=normalizedEmail(p.email),name=fullName(p.first_name,p.last_name).toLowerCase();return(entityEmail&&email===entityEmail)||(entityName&&name===entityName)})??null;const company=companies.find(item=>{const email=normalizedEmail(item.email),name=String(item.name??"").trim().toLowerCase();return(entityEmail&&email===entityEmail)||(entityName&&name===entityName)})??null;
 const filteredResponses=access.portal_type==="learner"?responseRows.filter(r=>normalizedEmail(r.respondent_email)===entityEmail):access.portal_type==="enterprise"?responseRows.filter(r=>normalizedEmail(r.respondent_email)===entityEmail||(entityName&&String(r.company_name??"").trim().toLowerCase()===entityName)):responseRows;
 const filteredConventions=access.portal_type==="learner"?conventionRows.filter(c=>c.recipient_type==="beneficiary"&&((entityEmail&&normalizedEmail(c.recipient_email)===entityEmail)||(entityName&&String(c.recipient_name??"").trim().toLowerCase()===entityName))):access.portal_type==="enterprise"?conventionRows.filter(c=>c.recipient_type==="company"&&((entityEmail&&normalizedEmail(c.recipient_email)===entityEmail)||(entityName&&String(c.company_name??"").trim().toLowerCase()===entityName))):[];
 const convocationRows=convocationsR.data??[];const filteredConvocations=access.portal_type==="learner"?convocationRows.filter(c=>c.recipient_type==="beneficiary"&&((entityEmail&&normalizedEmail(c.recipient_email)===entityEmail)||(entityName&&String(c.recipient_name??"").trim().toLowerCase()===entityName))):access.portal_type==="enterprise"?convocationRows.filter(c=>c.recipient_type==="company"&&((entityEmail&&normalizedEmail(c.recipient_email)===entityEmail)||(entityName&&String(c.company_name??"").trim().toLowerCase()===entityName))):convocationRows.filter(c=>c.recipient_type==="trainer");
 return NextResponse.json({access:{portalType:access.portal_type,roleLabel:portalRole(access.portal_type),entityName:access.entity_name,entityEmail:access.entity_email,viewedAt:access.viewed_at},session,onboarding:onboardingR.data,learner,company,companies:access.portal_type==="trainer"?companies:company?[company]:[],participants:access.portal_type==="enterprise"?asArray(company?.participants):access.portal_type==="trainer"?[...individualLearners,...companyLearners,...companies.flatMap(item=>asArray(item.participants))]:learner?[learner]:[],trainers:trainersR.data??[],responses:filteredResponses,conventions:filteredConventions,convocations:filteredConvocations,documents:learnerDocuments})
}
