"use client";

import Link from "next/link";
import { ChangeEvent, useEffect, useState } from "react";
import { assistanceFetch } from "@/components/AgentAssistanceBanner";
import LoadingMascot from "@/components/ui/LoadingMascot";

type Session={id:string;internal_reference?:string|null;start_date?:string|null;daily_formations?:{title?:string|null}|null};
const models=[
 {type:"training_agreement",label:"Convention de formation",detail:"Convention entre l'organisme et le client ou bénéficiaire."},
 {type:"convocation",label:"Convocation",detail:"Convocation individuelle à la session."},
 {type:"attendance_sheet",label:"Feuille d'émargement",detail:"Suivi des présences et signatures."},
 {type:"completion_certificate",label:"Attestation de fin de formation",detail:"Attestation remise à l'issue de la formation."},
 {type:"achievement_certificate",label:"Certificat de réalisation",detail:"Preuve de réalisation de l'action de formation."},
 {type:"internal_rules",label:"Règlement intérieur",detail:"Trame Selen du règlement applicable aux stagiaires."},
 {type:"welcome_booklet",label:"Livret d'accueil",detail:"Trame d'accueil et informations pratiques."},
];

export default function DailyDocumentModelsPage(){
 const[sessions,setSessions]=useState<Session[]>([]);const[sessionId,setSessionId]=useState("");const[beneficiary,setBeneficiary]=useState("");const[loading,setLoading]=useState(true);const[uploading,setUploading]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");
 useEffect(()=>{assistanceFetch("/api/client/daily/sessions",{cache:"no-store"}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Sessions indisponibles.");const rows=(d.sessions??[]).filter((x:{status?:string})=>x.status!=="archived");setSessions(rows);setSessionId(rows[0]?.id??"")}).catch(e=>setError(e instanceof Error?e.message:"Chargement impossible.")).finally(()=>setLoading(false))},[]);
 async function upload(type:string,event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(!sessionId){setError("Sélectionnez d'abord la session concernée.");return}setUploading(type);setError("");setMessage("");const form=new FormData();form.set("file",file);form.set("session_id",sessionId);form.set("document_type",type);form.set("beneficiary",beneficiary);const r=await assistanceFetch("/api/client/daily/manual-documents",{method:"POST",body:form});const d=await r.json().catch(()=>({}));if(r.ok)setMessage(`${models.find(m=>m.type===type)?.label??"Document"} importé comme nouvelle version (v${d.document?.version??"?"}).`);else setError(d.error??"Import impossible.");setUploading("")}
 if(loading)return <LoadingMascot message="Sélion ouvre les modèles de documents…"/>;
 return <main className="models-shell"><style>{css}</style><div className="models-wrap"><header><p className="kicker">SELEN DAILY</p><h1>Modèles de documents</h1><p className="lead">Daily utilise les modèles Selen pour garder des documents cohérents et faciles à archiver. Vous pouvez néanmoins télécharger chaque trame dans Word pour travailler hors connexion, puis réimporter ensuite votre document final en PDF.</p><div className="top-actions"><Link href="/client/daily/generateur-documents" className="primary">Générateur de documents PDF</Link></div></header>{error?<div className="error">{error}</div>:null}{message?<div className="success">{message}</div>:null}<section className="context card"><div><strong>Pour réimporter une version manuelle</strong><p>Choisissez la session à laquelle le PDF appartient. Le fichier importé devient une nouvelle version, l'ancienne reste conservée.</p></div><label>Session<select value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">Choisir une session</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.daily_formations?.title??"Formation"} · {s.internal_reference??s.start_date??s.id.slice(0,8)}</option>)}</select></label><label>Bénéficiaire, si le document est individuel<input value={beneficiary} onChange={e=>setBeneficiary(e.target.value)} placeholder="Nom et prénom"/></label></section><section className="grid">{models.map(model=><article className="card model" key={model.type}><div><span className="doc-icon">W</span><h2>{model.label}</h2><p>{model.detail}</p></div><div className="actions"><a className="secondary" href={`/api/client/daily/document-models/word?type=${encodeURIComponent(model.type)}`}>Télécharger le modèle Word</a><Link className="secondary" href={`/client/daily/generateur-documents?type=${encodeURIComponent(model.type)}`}>Générer en PDF</Link><label className={`upload ${!sessionId?"disabled":""}`}>{uploading===model.type?"Import en cours…":"Importer une autre version PDF"}<input hidden type="file" accept="application/pdf,.pdf" disabled={!sessionId||Boolean(uploading)} onChange={e=>void upload(model.type,e)}/></label></div></article>)}</section><aside className="note"><strong>Pourquoi le modèle Word ?</strong><p>Uniquement comme solution de continuité lorsque vous devez préparer un document sans connexion. Dans Daily, le générateur reste la voie normale : il reprend vos données organisme automatiquement et produit uniquement un PDF.</p></aside></div></main>
}
const css=`.models-shell{min-height:100vh;padding:2rem 1rem 5rem;background:linear-gradient(180deg,#eadfbf,#e0cf9f);color:#392a19}.models-wrap{max-width:1100px;margin:auto}.kicker{font:800 11px Arial,sans-serif;letter-spacing:.14em;color:#9b682d}.models-wrap h1{font:600 clamp(2rem,5vw,3rem) Georgia,serif;margin:.4rem 0}.lead{max-width:850px;color:#725e46;line-height:1.65}.top-actions{margin:1rem 0 1.4rem}.card{background:#f8f0dc;border:1px solid #d9c391;box-shadow:0 6px 18px rgba(57,42,25,.07)}.context{padding:1rem 1.2rem;display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:1rem;align-items:end;margin-bottom:1rem}.context p{margin:.3rem 0;color:#806c52;font-size:13px}.context label{display:grid;gap:5px;font-size:12px;font-weight:800}.context select,.context input{padding:.7rem;border:1px solid #cdb785;background:#fffaf0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1rem}.model{padding:1.2rem;display:grid;gap:1rem;align-content:space-between}.model h2{font:600 20px Georgia,serif;margin:.55rem 0}.model p{color:#806c52;line-height:1.5}.doc-icon{display:grid;place-items:center;width:34px;height:34px;background:#315d9d;color:white;font:bold 16px Arial}.actions{display:grid;gap:.5rem}.primary,.secondary,.upload{display:block;padding:.72rem .85rem;text-align:center;text-decoration:none;font-weight:800;cursor:pointer}.primary{width:fit-content;background:#7a2e22;color:#fff7e6;border:1px solid #7a2e22}.secondary,.upload{background:#fffaf0;color:#5c3a1e;border:1px solid #b99c70}.upload.disabled{opacity:.5;cursor:not-allowed}.note{margin-top:1rem;padding:1rem 1.2rem;border-left:4px solid #9b682d;background:rgba(248,240,220,.7)}.note p{margin-bottom:0;color:#725e46}.error,.success{padding:.8rem 1rem;margin:1rem 0}.error{border:1px solid #a64b3b;background:#fff2ee;color:#7d2e22}.success{border:1px solid #668153;background:rgba(102,129,83,.1);color:#455a3b}@media(max-width:760px){.context{grid-template-columns:1fr}}`;
