"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { assistanceFetch } from "@/components/AgentAssistanceBanner";

type Session = { id:string; internal_reference?:string|null; start_date?:string|null; end_date?:string|null; daily_formations?:{title?:string|null}|null };
type DocumentRow = { id:string; document_type:string; version:number; status:string; logical_name:string; linked_object_type:string; linked_object_id:string; metadata?:Record<string,unknown>|null; created_at:string };

const labels:Record<string,string> = { training_program:"Programme", training_agreement:"Convention", convocation:"Convocation", registration_positioning:"Inscription & positionnement" };
const statusLabels:Record<string,string> = { draft:"Brouillon", to_check:"À vérifier par Selen", to_validate:"À valider", validated:"Validé", published:"Publié", signed:"Signé", correction_requested:"Correction demandée", active:"Actif", archived:"Archivé" };
const sendableStatuses = new Set(["validated","published","active"]);

export default function DailyPretrainingDocumentsPage(){
  const [sessions,setSessions]=useState<Session[]>([]); const [sessionId,setSessionId]=useState(""); const [documents,setDocuments]=useState<DocumentRow[]>([]); const [loading,setLoading]=useState(true); const [generating,setGenerating]=useState(false); const [sendingId,setSendingId]=useState<string|null>(null); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  const load = useCallback(async()=>{ setLoading(true); setError(""); try { const s=await assistanceFetch("/api/client/daily/sessions",{cache:"no-store"}); const sd=await s.json().catch(()=>({})); if(!s.ok) throw new Error(sd.error??"Sessions indisponibles."); const rows=(sd.sessions??[]) as Session[]; setSessions(rows); setSessionId((current)=>current||rows[0]?.id||""); } catch(c){setError(c instanceof Error?c.message:"Chargement impossible.");} finally{setLoading(false);} },[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{ if(!sessionId){setDocuments([]);return;} void (async()=>{ const r=await assistanceFetch(`/api/client/daily/pretraining-documents?session_id=${encodeURIComponent(sessionId)}`,{cache:"no-store"}); const d=await r.json().catch(()=>({})); if(r.ok)setDocuments(d.documents??[]); else setError(d.error??"Documents indisponibles."); })(); },[sessionId]);
  const selected=useMemo(()=>sessions.find((s)=>s.id===sessionId)??null,[sessions,sessionId]);
  async function generate(event:FormEvent){ event.preventDefault(); if(!sessionId)return; setGenerating(true);setError("");setMessage(""); try{ const r=await assistanceFetch("/api/client/daily/pretraining-documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId})}); const d=await r.json().catch(()=>({})); if(!r.ok)throw new Error(d.error??"Génération impossible."); setMessage(`${d.count??0} document(s) généré(s) et transmis à Selen pour vérification.`); const refresh=await assistanceFetch(`/api/client/daily/pretraining-documents?session_id=${encodeURIComponent(sessionId)}`,{cache:"no-store"}); const rd=await refresh.json().catch(()=>({})); if(refresh.ok)setDocuments(rd.documents??[]); }catch(c){setError(c instanceof Error?c.message:"Génération impossible.");}finally{setGenerating(false);} }
  async function sendConvocation(document:DocumentRow){ setSendingId(document.id);setError("");setMessage(""); try{ const r=await assistanceFetch("/api/client/daily/pretraining-documents/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({document_id:document.id})}); const d=await r.json().catch(()=>({})); if(!r.ok)throw new Error(d.error??"Envoi impossible."); const evidenceText=d.evidenceRecorded===false?" L’e-mail est parti, mais la liaison technique de la preuve doit être contrôlée par Selen.":" La preuve d’envoi et la version exacte de la convocation sont conservées dans Communications."; setMessage(`Convocation envoyée à ${d.sentTo}.${evidenceText}`); }catch(c){setError(c instanceof Error?c.message:"Envoi impossible.");}finally{setSendingId(null);} }
  return <main style={{maxWidth:1100,margin:"0 auto",padding:"28px 20px"}}><p style={{fontSize:12,fontWeight:700,color:"var(--rust)"}}>SELEN DAILY</p><h1>Documents préformation</h1><p style={{color:"var(--ink-soft)",maxWidth:760}}>Générez les documents depuis les données de la session. Chaque nouvelle génération crée une version conservée dans l’historique et passe par une vérification Selen avant validation. Une convocation validée peut ensuite être envoyée directement à l’adresse enregistrée de l’apprenant, avec conservation automatique de la preuve d’envoi.</p>
    {error&&<div style={{padding:12,border:"1px solid #b24c3d",margin:"14px 0"}}>{error}</div>}{message&&<div style={{padding:12,border:"1px solid var(--sepia-mid)",margin:"14px 0"}}>{message}</div>}
    <form onSubmit={generate} style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end",margin:"22px 0"}}><label style={{display:"grid",gap:6,flex:"1 1 320px"}}>Session<select value={sessionId} onChange={(e)=>setSessionId(e.target.value)} disabled={loading||generating} style={{padding:10}}><option value="">Choisir une session</option>{sessions.map((s)=><option key={s.id} value={s.id}>{s.daily_formations?.title??"Formation"} · {s.internal_reference??s.start_date??"Session"}</option>)}</select></label><button type="submit" disabled={!sessionId||generating||Boolean(sendingId)} style={{padding:"11px 16px"}}>{generating?"Génération…":"Générer / régénérer les documents"}</button></form>
    {selected&&<div style={{padding:12,background:"rgba(201,160,85,.08)",border:"1px solid var(--sepia-mid)",marginBottom:18}}><strong>{selected.daily_formations?.title??"Formation"}</strong> · {selected.start_date??""} {selected.end_date&&selected.end_date!==selected.start_date?`→ ${selected.end_date}`:""}</div>}
    <section style={{display:"grid",gap:10}}>{documents.length===0?<div style={{padding:18,border:"1px solid var(--sepia-mid)"}}>Aucun document généré pour cette session.</div>:documents.map((doc)=>{ const canSend=doc.document_type==="convocation"&&sendableStatuses.has(doc.status); return <article key={doc.id} style={{padding:14,border:"1px solid var(--sepia-mid)",background:"var(--paper)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><strong>{labels[doc.document_type]??doc.document_type}</strong>{typeof doc.metadata?.learner_name==="string"?` · ${doc.metadata.learner_name}`:""}<div style={{fontSize:12,marginTop:4}}>Version {doc.version} · {statusLabels[doc.status]??doc.status}</div>{doc.document_type==="convocation"&&!canSend?<div style={{fontSize:12,marginTop:5,color:"var(--ink-soft)"}}>Envoi disponible après validation par Selen.</div>:null}</div><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><a href={`/api/client/daily/pretraining-documents/download?id=${encodeURIComponent(doc.id)}`} target="_blank" rel="noreferrer">Télécharger</a>{canSend?<button type="button" disabled={Boolean(sendingId)||generating} onClick={()=>void sendConvocation(doc)} style={{padding:"8px 11px",fontWeight:700}}>{sendingId===doc.id?"Envoi…":"Envoyer la convocation"}</button>:null}</div></div></article>;})}</section>
  </main>;
}
