import { NextResponse } from "next/server";
import { getDailyOrganisationBillingUserId, getDailyOrganisationReadContext } from "@/lib/server/dailyOrganisationContext";

type ActionItem={id:string;kind:"dossier"|"positioning"|"prerequisite"|"adaptation"|"trainer"|"onboarding"|"quality";priority:"high"|"medium"|"normal";title:string;detail:string;href:string;sessionId?:string|null;sessionLabel?:string|null};
type FormationRelation={title?:string|null};
type LearnerRelation={first_name?:string|null;last_name?:string|null};
type SessionRelation={id?:string|null;internal_reference?:string|null;status?:string|null;daily_formations?:FormationRelation|FormationRelation[]|null};
type EnrolmentRelation={id?:string|null;session_id?:string|null;status?:string|null;daily_learners?:LearnerRelation|LearnerRelation[]|null;daily_sessions?:SessionRelation|SessionRelation[]|null};
type SupportTask={key?:string|null;label?:string|null;status?:string|null};
type QualityAction={id:string;session_id?:string|null;category?:string|null;status?:string|null;title?:string|null;observation?:string|null;proposed_solution?:string|null};
function one<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]??null:value??null}
function sessionLabel(session:SessionRelation|null|undefined){const formation=one(session?.daily_formations);return session?.internal_reference||formation?.title||"Session"}
function learnerLabel(enrolment:EnrolmentRelation){const learner=one(enrolment.daily_learners);return [learner?.first_name,learner?.last_name].filter(Boolean).join(" ").trim()||"Apprenant"}
function monthBounds(){const now=new Date();const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));return{start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}}

export async function GET(req:Request){
 const context=await getDailyOrganisationReadContext(req,["sessions","trainings"]);if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});
 let billingUserId:string;try{billingUserId=await getDailyOrganisationBillingUserId(context.organisationId,context.user.id)}catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"Impossible de retrouver le paramétrage Daily."},{status:500})}
 const month=monthBounds();
 const[sessionsR,checklistR,enrolmentsR,needsR,onboardingR,businessWatchR,qualityActionsR]=await Promise.all([
  context.admin.from("daily_sessions").select("id,internal_reference,start_date,end_date,status,trainer_ids,daily_formations(title)").eq("organisation_id",context.organisationId).neq("status","archived").order("start_date",{ascending:true}),
  context.admin.from("daily_session_checklist_items").select("id,session_id,label,status,responsibility,due_at,note").eq("organisation_id",context.organisationId).neq("responsibility","selen"),
  context.admin.from("daily_session_enrolments").select("id,session_id,status,positioning_status,prerequisites_status,daily_learners(first_name,last_name),daily_sessions(id,internal_reference,start_date,end_date,status,daily_formations(title))").eq("organisation_id",context.organisationId).not("status","in","(cancelled,declined,completed)"),
  context.admin.from("daily_enrolment_support_needs").select("id,enrolment_id,has_specific_needs,needs_description,planned_accommodations,contact_requested,daily_session_enrolments(id,session_id,status,daily_learners(first_name,last_name),daily_sessions(id,internal_reference,start_date,end_date,status,daily_formations(title)))").eq("organisation_id",context.organisationId).eq("has_specific_needs",true),
  context.admin.from("daily_onboarding").select("support_tasks,qualiopi_status,quality_tracking_enabled").eq("user_id",billingUserId).maybeSingle(),
  context.admin.from("daily_business_watch_entries").select("id").eq("organisation_id",context.organisationId).gte("watch_date",month.start).lt("watch_date",month.end).limit(1),
  context.admin.from("daily_quality_actions").select("id,session_id,category,status,title,observation,proposed_solution").eq("organisation_id",context.organisationId).in("status",["open","planned"]).order("created_at",{ascending:true}),
 ]);
 const error=sessionsR.error??checklistR.error??enrolmentsR.error??needsR.error??onboardingR.error??businessWatchR.error??qualityActionsR.error;if(error)return NextResponse.json({error:error.message},{status:500});
 const sessions=sessionsR.data??[],checklist=checklistR.data??[],enrolments=enrolmentsR.data??[],supportNeeds=needsR.data??[],onboarding=onboardingR.data,qualityActions=(qualityActionsR.data??[]) as QualityAction[];const actions:ActionItem[]=[];const sessionsById=new Map(sessions.map(s=>[s.id,s]));
 const onboardingTasks=Array.isArray(onboarding?.support_tasks)?onboarding.support_tasks as SupportTask[]:[];
 for(const task of onboardingTasks){if(task.status!=="todo"||!task.label||task.key==="welcome_booklet")continue;const documentTask=["insee","qualiopi_certificate","nda_or_bpf"].includes(String(task.key));actions.push({id:`onboarding:${task.key??task.label}`,kind:"onboarding",priority:"medium",title:task.label,detail:"Cette pièce administrative manque encore dans le profil de votre organisme.",href:documentTask?"/client/daily/mon-compte#documents-organisme":"/client/daily/formateurs",sessionId:null,sessionLabel:"Profil organisme"})}
 for(const item of checklist){if(!["todo","in_progress","blocked"].includes(item.status))continue;const raw=sessionsById.get(item.session_id);if(!raw)continue;const session=raw as SessionRelation;actions.push({id:`dossier:${item.id}`,kind:"dossier",priority:item.status==="blocked"||Boolean(item.due_at&&new Date(item.due_at).getTime()<Date.now())?"high":"normal",title:item.label,detail:item.status==="blocked"?(item.note||"Ce point bloque actuellement le dossier de session."):"Ce point du dossier attend une action de votre organisme.",href:"/client/daily/dossiers",sessionId:item.session_id,sessionLabel:sessionLabel(session)})}
 for(const raw of enrolments){const enrolment=raw as EnrolmentRelation&{positioning_status?:string|null;prerequisites_status?:string|null};const session=one(enrolment.daily_sessions);if(!session||session.status==="archived")continue;const learner=learnerLabel(enrolment),label=sessionLabel(session);if(enrolment.positioning_status!=="reviewed")actions.push({id:`positioning:${enrolment.id}`,kind:"positioning",priority:enrolment.positioning_status==="submitted"?"medium":"normal",title:`Positionnement de ${learner}`,detail:enrolment.positioning_status==="submitted"?"Le positionnement a été reçu et doit être relu.":"Le positionnement n'est pas encore finalisé.",href:"/client/daily/apprenants",sessionId:enrolment.session_id,sessionLabel:label});if(enrolment.prerequisites_status!=="met"){const priority=enrolment.prerequisites_status==="not_met"?"high":enrolment.prerequisites_status==="to_clarify"?"medium":"normal";actions.push({id:`prerequisite:${enrolment.id}`,kind:"prerequisite",priority,title:`Prérequis de ${learner}`,detail:enrolment.prerequisites_status==="not_met"?"Les prérequis sont signalés comme non satisfaits.":enrolment.prerequisites_status==="to_clarify"?"Un point doit être clarifié sur les prérequis.":"Les prérequis doivent encore être vérifiés.",href:"/client/daily/apprenants",sessionId:enrolment.session_id,sessionLabel:label})}}
 for(const need of supportNeeds){const enrolment=one(need.daily_session_enrolments as EnrolmentRelation|EnrolmentRelation[]|null);if(!enrolment||["cancelled","declined","completed"].includes(enrolment.status??""))continue;const session=one(enrolment.daily_sessions);if(!session||session.status==="archived"||(need.planned_accommodations&&!need.contact_requested))continue;const learner=learnerLabel(enrolment);actions.push({id:`adaptation:${need.id}`,kind:"adaptation",priority:"high",title:`Adaptation à préparer pour ${learner}`,detail:need.contact_requested?"Un contact a été demandé pour préciser les besoins d'adaptation.":(need.needs_description||"Un besoin spécifique est signalé et les aménagements restent à préciser."),href:"/client/daily/apprenants",sessionId:enrolment.session_id,sessionLabel:sessionLabel(session)})}
 for(const raw of sessions){const trainerIds=Array.isArray(raw.trainer_ids)?raw.trainer_ids.filter(Boolean):[];if(trainerIds.length)continue;actions.push({id:`trainer:${raw.id}`,kind:"trainer",priority:"medium",title:"Formateur à associer",detail:"Cette session n'a pas encore de formateur associé.",href:"/client/daily/sessions",sessionId:raw.id,sessionLabel:sessionLabel(raw as SessionRelation)})}
 const qualityEnabled=onboarding?.qualiopi_status==="yes"||onboarding?.quality_tracking_enabled!==false;
 if(qualityEnabled&&(businessWatchR.data??[]).length===0)actions.push({id:`quality:business-watch:${month.start}`,kind:"quality",priority:"normal",title:"Compléter ma veille métier",detail:"Ajoutez au moins une veille métier ce mois-ci pour conserver une traçabilité régulière.",href:"/client/daily/qualite",sessionId:null,sessionLabel:"Suivi Qualité"});
 if(qualityEnabled)for(const item of qualityActions){const session=item.session_id?sessionsById.get(item.session_id):null;const sensitive=["incident","complaint"].includes(item.category??"");actions.push({id:`quality:action:${item.id}`,kind:"quality",priority:sensitive?"high":item.status==="open"?"medium":"normal",title:item.title?.trim()||"Action Qualité à suivre",detail:item.proposed_solution?.trim()||item.observation?.trim()||"Cette action Qualité reste à traiter ou à mettre en œuvre.",href:"/client/daily/qualite",sessionId:item.session_id??null,sessionLabel:session?sessionLabel(session as SessionRelation):"Suivi Qualité"})}
 const rank={high:0,medium:1,normal:2} as const;actions.sort((a,b)=>rank[a.priority]-rank[b.priority]||(a.sessionLabel??"").localeCompare(b.sessionLabel??"","fr"));
 return NextResponse.json({actions,counts:{total:actions.length,high:actions.filter(x=>x.priority==="high").length,dossier:actions.filter(x=>x.kind==="dossier").length,learners:actions.filter(x=>["positioning","prerequisite","adaptation"].includes(x.kind)).length,trainers:actions.filter(x=>x.kind==="trainer").length,onboarding:actions.filter(x=>x.kind==="onboarding").length,quality:actions.filter(x=>x.kind==="quality").length}})
}
