"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import LoadingMascot from "@/components/ui/LoadingMascot";
import { assistanceFetch } from "@/components/AgentAssistanceBanner";

type Session={id:string;start_date?:string|null;end_date?:string|null;modality?:string|null;location_address?:string|null;remote_url?:string|null;daily_formations?:{title?:string|null}|null};
type Org=Record<string,unknown>;
const types=[
 ["training_agreement","Convention de formation"],
 ["convocation","Convocation"],
 ["attendance_sheet","Feuille d'émargement"],
 ["completion_certificate","Attestation de fin de formation"],
 ["achievement_certificate","Certificat de réalisation"],
] as const;
function s(v:unknown){return String(v??"").trim()}
function frDate(v?:string|null){if(!v)return "À définir";return new Intl.DateTimeFormat("fr-FR").format(new Date(`${v}T12:00:00`))}
function period(session?:Session|null){if(!session)return "À définir";const a=frDate(session.start_date),b=frDate(session.end_date||session.start_date);return a===b?a:`${a} au ${b}`}

export default function DailyDocumentGeneratorPage(){
 const[org,setOrg]=useState<Org>({});const[sessions,setSessions]=useState<Session[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[type,setType]=useState<(typeof types)[number][0]>("training_agreement");const[sessionId,setSessionId]=useState("");
 useEffect(()=>{Promise.all([assistanceFetch("/api/client/daily/workspace",{cache:"no-store"}),assistanceFetch("/api/client/daily/sessions",{cache:"no-store"})]).then(async([wr,sr])=>{const w=await wr.json().catch(()=>({}));const ss=await sr.json().catch(()=>({}));if(!wr.ok||!sr.ok)throw new Error("Impossible de charger le générateur.");setOrg(w.workspace?.organisation??{});setSessions((ss.sessions??[]).filter((x:{status?:string})=>x.status!=="archived"));}).catch(e=>setError(e instanceof Error?e.message:"Chargement impossible.")).finally(()=>setLoading(false))},[]);
 const session=useMemo(()=>sessions.find(x=>x.id===sessionId)??null,[sessions,sessionId]);
 const organisation=s(org.legal_name||org.name)||"Organisme non renseigné";const siret=s(org.siret)||"SIRET non renseigné";const address=s(org.administrative_address||org.address)||"Adresse non renseignée";const nda=s(org.nda_number);
 function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!session){setError("Sélectionnez une session.");return}const f=new FormData(e.currentTarget);const beneficiary=s(f.get("beneficiary"));if(!beneficiary){setError("Nom du bénéficiaire requis.");return}const company=s(f.get("company"));const beneficiaryAddress=s(f.get("beneficiary_address"));const title=session.daily_formations?.title??"Formation";const doc=new jsPDF();const label=types.find(x=>x[0]===type)?.[1]??"Document";let y=22;doc.setFont("helvetica","bold");doc.setFontSize(18);doc.text(label.toUpperCase(),20,y);y+=14;doc.setFontSize(10);doc.setFont("helvetica","normal");const lines=[`Organisme de formation : ${organisation}`,`SIRET : ${siret}`,`Adresse : ${address}`,nda?`NDA : ${nda}`:"",`Bénéficiaire : ${beneficiary}`,company?`Entreprise : ${company}`:"",beneficiaryAddress?`Adresse du bénéficiaire : ${beneficiaryAddress}`:"",`Formation : ${title}`,`Dates : ${period(session)}`,`Modalité / lieu : ${session.location_address||session.remote_url||session.modality||"À définir"}`].filter(Boolean);for(const line of lines){for(const part of doc.splitTextToSize(line,170) as string[]){doc.text(part,20,y);y+=6}}
 y+=6;doc.setFont("helvetica","bold");if(type==="training_agreement")doc.text("Objet de la convention",20,y);else if(type==="convocation")doc.text("Convocation",20,y);else if(type==="attendance_sheet")doc.text("Émargement",20,y);else doc.text("Attestation",20,y);y+=8;doc.setFont("helvetica","normal");const body=type==="training_agreement"?`La présente convention concerne l'action de formation « ${title} » au bénéfice de ${beneficiary}. Les conditions pédagogiques, financières et d'organisation applicables sont celles enregistrées pour la session sélectionnée dans Selen Daily.`:type==="convocation"?`${beneficiary} est convoqué(e) à l'action de formation « ${title} » pour la période ${period(session)}.`:type==="attendance_sheet"?`Présence de ${beneficiary} à la formation « ${title} ».\n\nSignature bénéficiaire : ____________________\n\nSignature formateur : ____________________`:type==="completion_certificate"?`Je soussigné(e), représentant ${organisation}, atteste que ${beneficiary} a suivi la formation « ${title} » sur la période ${period(session)}.`:`Je soussigné(e), représentant ${organisation}, certifie que ${beneficiary} a réalisé l'action de formation « ${title} » sur la période ${period(session)}.`;for(const part of doc.splitTextToSize(body,170) as string[]){doc.text(part,20,y);y+=6}y+=12;doc.text(`Fait le ${new Intl.DateTimeFormat("fr-FR").format(new Date())}`,20,y);y+=8;doc.text("Signature de l'organisme : ______________________________",20,y);doc.setFontSize(7);doc.setTextColor(100);doc.text(`${organisation} · SIRET ${siret} · ${address}`,20,285,{maxWidth:170});doc.save(`${label.replace(/[^a-zA-Z0-9]+/g,"_")}_${beneficiary.replace(/[^a-zA-Z0-9]+/g,"_")}.pdf`)}
 if(loading)return <LoadingMascot message="Sélion prépare le générateur de documents…"/>;
 return <main style={{maxWidth:900,margin:"0 auto",padding:"2rem 1rem 5rem"}}><p style={{color:"var(--rust)",fontWeight:800,fontSize:12}}>SELEN DAILY</p><h1>Générateur de documents</h1><p style={{color:"var(--ink-soft)",lineHeight:1.6}}>Les informations de votre organisme sont reprises automatiquement et ne peuvent pas être modifiées ici. Renseignez uniquement le bénéficiaire puis téléchargez le document en PDF.</p>{error?<div style={{border:"1px solid #a64b3b",padding:12,margin:"1rem 0",color:"#7d2e22"}}>{error}</div>:null}<section style={{border:"1px solid var(--sepia-mid)",background:"var(--paper)",padding:"1rem",margin:"1rem 0"}}><strong>Identité utilisée dans les documents</strong><p>{organisation}<br/>SIRET : {siret}<br/>{address}{nda?<><br/>NDA : {nda}</>:null}</p></section><form onSubmit={generate} style={{display:"grid",gap:"1rem",border:"1px solid var(--sepia-mid)",background:"var(--paper)",padding:"1.25rem"}}><label>Document<select value={type} onChange={e=>setType(e.target.value as typeof type)} style={field}>{types.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Session<select required value={sessionId} onChange={e=>setSessionId(e.target.value)} style={field}><option value="">Choisir une session</option>{sessions.map(x=><option value={x.id} key={x.id}>{x.daily_formations?.title??"Formation"} · {x.start_date??"date à définir"}</option>)}</select></label><label>Nom et prénom du bénéficiaire *<input name="beneficiary" required style={field}/></label><label>Entreprise du bénéficiaire<input name="company" style={field}/></label><label>Adresse du bénéficiaire<input name="beneficiary_address" style={field}/></label><button type="submit" style={{padding:".8rem 1rem",fontWeight:800}}>Télécharger le PDF</button></form></main>
}
const field:React.CSSProperties={display:"block",width:"100%",marginTop:6,padding:10,border:"1px solid var(--sepia-mid)",background:"white"};
