"use client";

import { ChangeEvent, useEffect, useState } from "react";
import LoadingMascot from "@/components/ui/LoadingMascot";

type WorkspaceResponse={workspace?:{organisation?:Record<string,unknown>}};
type OnboardingResponse={onboarding?:Record<string,unknown>;subscription?:Record<string,unknown>|null};
function text(v:unknown){return String(v??"")}
function money(cents:unknown){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(cents??6900)/100)}

type DocType="insee"|"qualiopi"|"bpf";

export default function DailyAccountPanel(){
 const[workspace,setWorkspace]=useState<WorkspaceResponse["workspace"]|null>(null);const[onboarding,setOnboarding]=useState<Record<string,unknown>|null>(null);const[subscription,setSubscription]=useState<Record<string,unknown>|null>(null);const[form,setForm]=useState({administrative_email:"",administrative_phone:"",administrative_address:""});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState<DocType|null>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");
 async function load(){const[wr,or]=await Promise.all([fetch("/api/client/daily/workspace",{cache:"no-store"}),fetch("/api/client/daily/onboarding",{cache:"no-store"})]);const wb=await wr.json().catch(()=>({})) as WorkspaceResponse;const ob=await or.json().catch(()=>({})) as OnboardingResponse;if(!wr.ok||!or.ok)throw new Error("Impossible de charger votre compte Daily.");const ws=wb.workspace??null;const org=ws?.organisation??{};setWorkspace(ws);setOnboarding(ob.onboarding??null);setSubscription(ob.subscription??null);setForm({administrative_email:text(org.administrative_email),administrative_phone:text(org.administrative_phone),administrative_address:text(org.administrative_address||org.address)})}
 useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Chargement impossible.")).finally(()=>setLoading(false))},[]);
 async function save(){setSaving(true);setError("");setMessage("");const r=await fetch("/api/client/daily/workspace",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update_safe_profile",values:form})});const b=await r.json().catch(()=>({}));if(r.ok){setWorkspace(b.workspace??workspace);setMessage("Informations administratives mises à jour.")}else setError(b.error??"Modification impossible.");setSaving(false)}
 async function upload(type:DocType,event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setUploading(type);setError("");setMessage("");const body=new FormData();body.set("type",type);body.set("file",file);const r=await fetch("/api/client/daily/organisation-documents",{method:"POST",body});const b=await r.json().catch(()=>({}));if(!r.ok)setError(b.error??"Import impossible.");else{await load();setMessage("Document enregistré dans le profil de votre organisme.")}event.target.value="";setUploading(null)}
 async function billing(){setError("");const r=await fetch("/api/client/daily/billing-portal",{method:"POST"});const b=await r.json().catch(()=>({}));if(!r.ok||!b.url){setError(b.error??"Portail de facturation indisponible.");return}window.location.href=b.url}
 if(loading)return <LoadingMascot message="Sélion ouvre votre profil et votre organisme…"/>;
 const org=workspace?.organisation??{};const name=text(org.legal_name||org.name||onboarding?.organisation_name||"Mon organisme");const isQualiopi=text(org.qualiopi_status||onboarding?.qualiopi_status)==="yes";const firstNdaYear=Boolean(onboarding?.first_nda_year);const hasNda=Boolean(text(org.nda_number||onboarding?.nda_number).trim());
 const docs:Array<{type:DocType;label:string;url:unknown;help:string;required:boolean}>=[
  {type:"insee",label:"Avis INSEE",url:onboarding?.insee_document_url,help:"Pièce d'identification de l'organisme",required:true},
  {type:"qualiopi",label:"Certificat Qualiopi",url:onboarding?.qualiopi_certificate_url,help:isQualiopi?"À conserver à jour":"Non requis si vous n'êtes pas certifié",required:isQualiopi},
  {type:"bpf",label:"Dernier BPF",url:onboarding?.nda_or_bpf_document_url,help:!hasNda?"Non requis tant que l'organisme n'a pas de NDA":firstNdaYear?"Non requis pour la première année de NDA":"Dernier bilan pédagogique et financier",required:hasNda&&!firstNdaYear},
 ];
 return <main className="acc-shell"><style>{css}</style><div className="acc-wrap"><header className="acc-head"><div><span className="acc-kicker">Mon espace client</span><h1>Profil & organisme de formation</h1><p>Tout ce qui concerne votre organisme, vos pièces administratives et votre abonnement Daily est regroupé ici.</p></div></header>{message?<div className="acc-success">{message}</div>:null}{error?<div className="acc-error">{error}</div>:null}
 <section className="acc-grid"><article className="card"><h2>Identité de l'organisme</h2><Info label="Raison sociale" value={name}/><Info label="SIRET" value={text(org.siret||onboarding?.siret)||"Non renseigné"}/><Info label="NDA" value={text(org.nda_number||onboarding?.nda_number)||"Non renseigné"}/><Info label="Qualiopi" value={isQualiopi?"Certifié Qualiopi":text(org.qualiopi_status||onboarding?.qualiopi_status)||"Non renseigné"}/><p className="note">Les changements juridiques sensibles sont contrôlés afin de préserver l'historique de conformité.</p></article><article className="card"><h2>Coordonnées administratives</h2><Field label="Email administratif" value={form.administrative_email} onChange={v=>setForm({...form,administrative_email:v})}/><Field label="Téléphone" value={form.administrative_phone} onChange={v=>setForm({...form,administrative_phone:v})}/><Field label="Adresse administrative" value={form.administrative_address} onChange={v=>setForm({...form,administrative_address:v})}/><button type="button" onClick={save} disabled={saving} className="primary">{saving?"Enregistrement…":"Enregistrer"}</button></article></section>
 <section className="card" id="documents-organisme"><div className="section-title"><div><span className="acc-kicker">Pièces permanentes</span><h2>Documents de mon organisme</h2><p className="note">Les pièces demandées dans votre liste de tâches se déposent ici. Le livret d'accueil n'est pas à fournir : Daily utilise le modèle Selen.</p></div></div><div className="doc-grid">{docs.map(doc=><div className={`doc ${doc.url?"ok":doc.required?"missing":"optional"}`} key={doc.type}><strong>{doc.url?"✓ ":doc.required?"! ":"· "}{doc.label}</strong><small>{doc.help}</small>{doc.url?<a href={text(doc.url)} target="_blank" rel="noreferrer">Voir le document →</a>:null}{doc.required||doc.type==="qualiopi"?<label className="upload">{uploading===doc.type?"Import en cours…":doc.url?"Remplacer le document":"Déposer le document"}<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={uploading!==null} onChange={e=>void upload(doc.type,e)}/></label>:null}</div>)}</div></section>
 <section className="card"><span className="acc-kicker">Abonnement</span><h2>Selen Daily</h2><div className="sub-grid"><Info label="Statut" value={text(subscription?.status||"actif")}/><Info label="Formule" value={text(subscription?.current_tier||"Daily")}/><Info label="Mensualité actuelle" value={money(subscription?.base_monthly_amount_cents||6900)}/><Info label="Période annuelle" value={`${text(subscription?.annual_period_start)||"—"} → ${text(subscription?.annual_period_end)||"—"}`}/></div><button type="button" onClick={billing} className="primary">Gérer ma carte ou mon abonnement</button><p className="note">Les factures sont gérées par Selen depuis le Studio. Elles ne sont pas générées depuis cet espace client.</p></section>
 </div></main>
}
function Info({label,value}:{label:string;value:string}){return <div className="info"><span>{label}</span><strong>{value}</strong></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>}
const css=`.acc-shell{min-height:100vh;background:linear-gradient(180deg,#eadfbf,#e0cf9f);color:#392a19;padding:2rem 1rem 5rem}.acc-wrap{max-width:1050px;margin:auto;display:grid;gap:1rem}.acc-head,.card{background:#f8f0dc;border:1px solid #d9c391;box-shadow:0 8px 20px rgba(57,42,25,.08)}.acc-head{padding:1.7rem 1.9rem}.acc-head h1{font:600 clamp(2rem,5vw,3rem) Georgia,serif;margin:.35rem 0}.acc-head p{color:#725e46;line-height:1.6;max-width:720px}.acc-kicker{text-transform:uppercase;letter-spacing:.14em;font:800 11px Arial,sans-serif;color:#9b682d}.acc-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{padding:1.4rem 1.5rem}.card h2{font-family:Georgia,serif;margin:.35rem 0 1rem}.info{display:grid;gap:4px;border-bottom:1px solid rgba(160,106,44,.2);padding:.7rem 0}.info span,.field span{color:#806c52;font-size:12px;font-weight:700}.field{display:grid;gap:5px;margin-bottom:.8rem}.field input{border:1px solid #cdb785;background:#fffaf0;padding:.7rem;color:#392a19}.primary{border:1px solid #7a2e22;background:#7a2e22;color:#f8f0dc;padding:.75rem 1rem;font-weight:800;cursor:pointer}.note{color:#7d6a51;font-size:13px;line-height:1.55}.section-title{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.doc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:.7rem}.doc{border:1px solid rgba(160,106,44,.22);padding:.9rem;display:grid;gap:7px;background:rgba(255,250,240,.55)}.doc.ok{border-left:4px solid #6f8b58}.doc.missing{border-left:4px solid #a64b3b}.doc.optional{border-left:4px solid #b99c70}.doc small{color:#806c52}.doc a{color:#7a2e22;font-weight:800;text-decoration:none}.upload{display:inline-flex;width:fit-content;border:1px solid #7a2e22;background:#fffaf0;color:#7a2e22;padding:.55rem .7rem;font-weight:800;cursor:pointer}.upload input{display:none}.sub-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:0 1rem;margin-bottom:1rem}.acc-success{border:1px solid #668153;background:rgba(102,129,83,.1);padding:.8rem;color:#455a3b}.acc-error{border:1px solid #a64b3b;background:#fff2ee;padding:.8rem;color:#7d2e22}@media(max-width:760px){.acc-grid{grid-template-columns:1fr}.section-title{display:grid}}`;