"use client";

import { useEffect, useState } from "react";

type Mode="immediate"|"daily_digest";
export default function DailyReminderPreferences(){
 const[mode,setMode]=useState<Mode>("daily_digest");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/client/daily/reminder-preferences",{cache:"no-store"}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??"Préférences indisponibles.");setMode(b.mode==="immediate"?"immediate":"daily_digest")}).catch(e=>setError(e instanceof Error?e.message:"Chargement impossible.")).finally(()=>setLoading(false))},[]);
 async function save(next:Mode){setSaving(true);setError("");setMessage("");const r=await fetch("/api/client/daily/reminder-preferences",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:next})});const b=await r.json().catch(()=>({}));if(r.ok){setMode(next);setMessage("Préférence de rappel enregistrée.")}else setError(b.error??"Modification impossible.");setSaving(false)}
 return <section style={s.card}><p style={s.kicker}>Rappels de tâches</p><h2 style={s.h2}>Comment souhaitez-vous être prévenu ?</h2><p style={s.text}>Cette préférence concerne les tâches qui nécessitent réellement votre intervention dans Daily.</p>{loading?<p style={s.text}>Chargement…</p>:<div style={s.options}><button type="button" disabled={saving} onClick={()=>void save("immediate")} style={mode==="immediate"?s.active:s.option}><strong>Au fil de l'eau</strong><span>Un email dès qu'une nouvelle tâche requiert votre attention.</span></button><button type="button" disabled={saving} onClick={()=>void save("daily_digest")} style={mode==="daily_digest"?s.active:s.option}><strong>Une fois par jour à 7 h</strong><span>Un seul récapitulatif des tâches encore ouvertes. Aucun email si tout est à jour.</span></button></div>}{message?<p style={s.ok}>{message}</p>:null}{error?<p style={s.error}>{error}</p>:null}</section>
}
const s:Record<string,React.CSSProperties>={card:{maxWidth:1050,margin:"1rem auto 0",background:"#f8f0dc",border:"1px solid #d9c391",padding:"1.4rem 1.5rem",color:"#392a19",boxShadow:"0 8px 20px rgba(57,42,25,.08)"},kicker:{textTransform:"uppercase",letterSpacing:".14em",fontSize:11,fontWeight:800,color:"#9b682d"},h2:{fontFamily:"Georgia,serif",margin:".35rem 0"},text:{color:"#725e46",lineHeight:1.55},options:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:10,marginTop:12},option:{display:"grid",gap:5,textAlign:"left",border:"1px solid #cdb785",background:"#fffaf0",padding:"1rem",color:"#392a19",cursor:"pointer"},active:{display:"grid",gap:5,textAlign:"left",border:"2px solid #7a2e22",background:"rgba(122,46,34,.07)",padding:"calc(1rem - 1px)",color:"#392a19",cursor:"pointer"},ok:{color:"#455a3b",fontWeight:700},error:{color:"#7d2e22",fontWeight:700}};
