"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import LoadingMascot from "@/components/ui/LoadingMascot";

type LearnerSat={id:string;overall_rating:number|null;strengths:string|null;improvements:string|null;free_comment:string|null;submitted_at:string|null};
type StakeholderSat={id:string;stakeholder_type:string|null;entity_name:string|null;overall_rating:number|null;strengths:string|null;improvements:string|null;free_comment:string|null;submitted_at:string|null};
type Feedback={id:string;submission_type:string|null;stakeholder_type:string|null;submitter_name:string|null;subject:string|null;message:string|null;status:string|null;organisation_response:string|null;created_at:string|null};
type Action={id:string;category:string;title:string;observation:string|null;proposed_solution:string|null;implemented_improvement:string|null;status:string;implemented_at:string|null;created_at:string|null};
type Overview={learnerSatisfaction:LearnerSat[];stakeholderSatisfaction:StakeholderSat[];feedback:Feedback[];actions:Action[]};
type Tab="satisfactions"|"incidents"|"reclamations"|"correctives"|"ameliorations";
const tabs:{id:Tab;label:string}[]=[{id:"satisfactions",label:"Satisfactions"},{id:"incidents",label:"Incidents & difficultés"},{id:"reclamations",label:"Réclamations"},{id:"correctives",label:"Actions correctives"},{id:"ameliorations",label:"Améliorations"}];
const fr=(v?:string|null)=>v?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(new Date(v)):"—";
const txt=(v?:string|null)=>v?.trim()||"—";

export default function DailyQualityPilotagePage(){
 const[data,setData]=useState<Overview|null>(null);const[tab,setTab]=useState<Tab>("satisfactions");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get("tab") as Tab|null;if(p&&tabs.some(x=>x.id===p))setTab(p);void(async()=>{try{const r=await fetch("/api/client/daily/quality-overview",{cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??"Pilotage qualité indisponible.");setData({learnerSatisfaction:b.learnerSatisfaction??[],stakeholderSatisfaction:b.stakeholderSatisfaction??[],feedback:b.feedback??[],actions:b.actions??[]})}catch(e){setError(e instanceof Error?e.message:"Chargement impossible.")}finally{setLoading(false)}})()},[]);
 const learner=data?.learnerSatisfaction??[],stakeholders=data?.stakeholderSatisfaction??[],feedback=data?.feedback??[],actions=data?.actions??[];
 const satisfactionRows=useMemo(()=>[...learner.map(x=>({id:`l-${x.id}`,who:"Apprenant",rating:x.overall_rating,strengths:x.strengths,improvements:x.improvements,comment:x.free_comment,date:x.submitted_at})),...stakeholders.map(x=>({id:`s-${x.id}`,who:x.entity_name||x.stakeholder_type||"Partie prenante",rating:x.overall_rating,strengths:x.strengths,improvements:x.improvements,comment:x.free_comment,date:x.submitted_at}))],[learner,stakeholders]);
 const incidentActions=actions.filter(x=>["incident","difficulty"].includes(x.category));
 const complaintActions=actions.filter(x=>x.category==="complaint");
 const complaintFeedback=feedback.filter(x=>String(x.submission_type??"").toLowerCase().includes("complaint")||String(x.submission_type??"").toLowerCase().includes("reclamation")||String(x.subject??"").toLowerCase().includes("réclam"));
 const corrective=actions.filter(x=>x.category==="corrective_action");
 const improvements=actions.filter(x=>x.category==="improvement");
 if(loading)return <LoadingMascot message="Sélion consolide les éléments qualité…"/>;
 return <main style={s.page}><div style={s.wrap}><header style={s.card}><p style={s.kicker}>Selen Daily · Qualité</p><h1 style={s.h1}>Pilotage qualité</h1><p style={s.muted}>Chaque rubrique reprend l’ensemble des éléments remontés dans Daily. Les procédures internes ont leur propre espace et ne sont donc plus mélangées au pilotage.</p></header>{error?<p style={s.error}>{error}</p>:null}<div style={s.tabs}>{tabs.map(x=><Link key={x.id} href={`/client/daily/qualite/pilotage?tab=${x.id}`} onClick={()=>setTab(x.id)} style={{...s.tab,...(tab===x.id?s.tabActive:{})}}>{x.label}</Link>)}</div>{tab==="satisfactions"?<Table headers={["Origine","Note","Points forts","À améliorer","Commentaire","Date"]} rows={satisfactionRows.map(x=>[x.who,typeof x.rating==="number"?`${x.rating}/10`:"—",txt(x.strengths),txt(x.improvements),txt(x.comment),fr(x.date)])} empty="Aucune satisfaction reçue."/>:null}{tab==="incidents"?<Table headers={["Type","Titre","Constat","Solution","Amélioration","Statut","Date"]} rows={incidentActions.map(x=>[x.category==="incident"?"Incident":"Difficulté",x.title,txt(x.observation),txt(x.proposed_solution),txt(x.implemented_improvement),x.status,fr(x.created_at)])} empty="Aucun incident ou difficulté enregistré."/>:null}{tab==="reclamations"?<><Table headers={["Source","Sujet","Émetteur","Message","Réponse","Statut","Date"]} rows={complaintFeedback.map(x=>[x.submission_type||"Réclamation",txt(x.subject),x.submitter_name||x.stakeholder_type||"—",txt(x.message),txt(x.organisation_response),x.status||"à traiter",fr(x.created_at)])} empty="Aucune réclamation remontée par les parties prenantes."/><Table headers={["Action liée","Constat","Solution","Amélioration","Statut","Date"]} rows={complaintActions.map(x=>[x.title,txt(x.observation),txt(x.proposed_solution),txt(x.implemented_improvement),x.status,fr(x.created_at)])} empty="Aucune action de type réclamation enregistrée."/></>:null}{tab==="correctives"?<Table headers={["Action","Constat","Solution proposée","Mise en œuvre","Statut","Date"]} rows={corrective.map(x=>[x.title,txt(x.observation),txt(x.proposed_solution),txt(x.implemented_improvement),x.status,fr(x.created_at)])} empty="Aucune action corrective enregistrée."/>:null}{tab==="ameliorations"?<Table headers={["Amélioration","Constat","Solution proposée","Mise en œuvre","Statut","Date"]} rows={improvements.map(x=>[x.title,txt(x.observation),txt(x.proposed_solution),txt(x.implemented_improvement),x.status,fr(x.created_at)])} empty="Aucune amélioration enregistrée."/>:null}</div></main>}
function Table({headers,rows,empty}:{headers:string[];rows:string[][];empty:string}){return <section style={s.card}><div style={s.tableWrap}>{rows.length?<table style={s.table}><thead><tr>{headers.map(h=><th key={h} style={s.th}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={s.td}>{c}</td>)}</tr>)}</tbody></table>:<p style={s.muted}>{empty}</p>}</div></section>}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",padding:"1rem 1rem 5rem",color:"#392a19"},wrap:{maxWidth:1180,margin:"auto",display:"grid",gap:16},card:{background:"#f8f0dc",border:"1px solid #d9c391",padding:"1.25rem",boxShadow:"0 8px 20px rgba(57,42,25,.08)"},kicker:{textTransform:"uppercase",letterSpacing:".12em",fontSize:10,fontWeight:800,color:"#9b682d"},h1:{fontFamily:"Georgia,serif",fontSize:"clamp(2rem,5vw,3rem)",margin:".3rem 0"},muted:{color:"#725e46",lineHeight:1.55},tabs:{display:"flex",gap:8,flexWrap:"wrap"},tab:{border:"1px solid #d9c391",background:"#fffaf0",padding:".55rem .75rem",color:"#7a2e22",fontWeight:800,textDecoration:"none"},tabActive:{background:"#7a2e22",color:"#fff8e8",borderColor:"#7a2e22"},tableWrap:{overflowX:"auto"},table:{width:"100%",borderCollapse:"collapse",minWidth:760},th:{textAlign:"left",padding:10,borderBottom:"2px solid #cdb785",background:"#efe3cf",fontSize:12},td:{verticalAlign:"top",padding:10,borderBottom:"1px solid #e2d2ad",whiteSpace:"pre-wrap",fontSize:13,lineHeight:1.45},error:{border:"1px solid #a64b3b",padding:10,color:"#7d2e22",background:"#fff2ee"}};
