"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import LoadingMascot from "@/components/ui/LoadingMascot";

type Slot={startsAt:string;endsAt:string;label:string};
type NextAvailable={date:string;slot:Slot}|null;
function today(){return new Date().toISOString().slice(0,10)}
function formatDate(value:string){return new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(`${value}T12:00:00`))}

export default function DailySetupAppointmentPage(){
 const[date,setDate]=useState(today());const[slots,setSlots]=useState<Slot[]>([]);const[selected,setSelected]=useState<Slot|null>(null);const[nextAvailable,setNextAvailable]=useState<NextAvailable>(null);const[firstName,setFirstName]=useState("");const[lastName,setLastName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);const[error,setError]=useState("");const[done,setDone]=useState(false);
 useEffect(()=>{let cancelled=false;fetch("/api/client/daily/setup-appointment?next=1",{cache:"no-store"}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??"Créneaux indisponibles.");if(cancelled)return;setNextAvailable(b.nextAvailable??null);setFirstName(v=>v||b.profile?.firstName||"");setLastName(v=>v||b.profile?.lastName||"");setEmail(b.profile?.email||"");if(b.nextAvailable?.date){setDate(b.nextAvailable.date);setSelected(b.nextAvailable.slot??null)}}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"Chargement impossible.")});return()=>{cancelled=true}},[]);
 useEffect(()=>{let cancelled=false;setLoading(true);fetch(`/api/client/daily/setup-appointment?date=${encodeURIComponent(date)}`,{cache:"no-store"}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??"Créneaux indisponibles.");if(cancelled)return;setSlots(b.slots??[]);setFirstName(v=>v||b.profile?.firstName||"");setLastName(v=>v||b.profile?.lastName||"");setEmail(b.profile?.email||"");setSelected(current=>current&&b.slots?.some((slot:Slot)=>slot.startsAt===current.startsAt)?current:null)}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"Chargement impossible.")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[date]);
 async function book(){if(!selected)return;setSubmitting(true);setError("");const r=await fetch("/api/client/daily/setup-appointment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({firstName,lastName,phone,message,startsAt:selected.startsAt,endsAt:selected.endsAt})});const b=await r.json().catch(()=>({}));if(!r.ok)setError(b.error??"Réservation impossible.");else setDone(true);setSubmitting(false)}
 if(loading)return <LoadingMascot message="Sélion consulte les créneaux disponibles…"/>;
 if(done)return <main style={s.page}><div style={s.wrap}><section style={s.card}><p style={s.kicker}>Rendez-vous confirmé</p><h1 style={s.h1}>Votre visio de paramétrage est réservée</h1><p style={s.lead}>Le rendez-vous dure une heure. Vous recevrez également l'invitation Google Calendar avec le lien de visioconférence.</p><div style={s.actions}><Link href="/client/daily" style={s.secondary}>Retour au tableau de bord</Link></div></section></div></main>;
 return <main style={s.page}><div style={s.wrap}><header style={s.hero}><p style={s.kicker}>Paramétrage accompagné</p><h1 style={s.h1}>Réserver une visio d'une heure</h1><p style={s.lead}>Le prochain créneau disponible vous est proposé en priorité. Vous pouvez aussi choisir une autre date.</p></header>{error?<p style={s.error}>{error}</p>:null}{nextAvailable?<section style={s.nextCard}><p style={s.kicker}>Prochain créneau disponible</p><strong style={s.nextTitle}>{formatDate(nextAvailable.date)} · {nextAvailable.slot.label}</strong><button type="button" style={s.primary} onClick={()=>{setDate(nextAvailable.date);setSelected(nextAvailable.slot)}}>Choisir ce créneau</button></section>:null}<section style={s.card}><div style={s.grid}><label style={s.field}><span>Prénom</span><input value={firstName} onChange={e=>setFirstName(e.target.value)} style={s.input}/></label><label style={s.field}><span>Nom</span><input value={lastName} onChange={e=>setLastName(e.target.value)} style={s.input}/></label><label style={s.field}><span>Email du compte</span><input value={email} disabled style={{...s.input,opacity:.7}}/></label><label style={s.field}><span>Téléphone</span><input value={phone} onChange={e=>setPhone(e.target.value)} style={s.input}/></label></div><label style={s.field}><span>Précision utile, facultatif</span><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} style={s.input}/></label><label style={s.field}><span>Autre date</span><input type="date" min={today()} value={date} onChange={e=>{setDate(e.target.value);setSelected(null)}} style={s.input}/></label><div style={s.slotGrid}>{slots.length?slots.map(slot=><button key={slot.startsAt} type="button" onClick={()=>setSelected(slot)} style={selected?.startsAt===slot.startsAt?s.slotOn:s.slot}>{slot.label}</button>):<p style={s.muted}>Aucun créneau disponible ce jour. Les rendez-vous sont proposés le mardi, mercredi matin et jeudi selon les disponibilités du calendrier.</p>}</div><button type="button" disabled={!selected||!firstName||!lastName||!phone||submitting} onClick={book} style={{...s.primary,border:"1px solid #7a2e22",cursor:selected?"pointer":"not-allowed",opacity:selected?1:.55}}>{submitting?"Réservation…":"Confirmer ce rendez-vous d'une heure"}</button></section></div></main>
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"linear-gradient(180deg,#eadfbf,#e0cf9f)",padding:"2rem 1rem 5rem",color:"#392a19"},wrap:{maxWidth:900,margin:"0 auto",display:"grid",gap:"1rem"},hero:{background:"#f8f0dc",border:"1px solid #d9c391",padding:"1.8rem"},card:{background:"#f8f0dc",border:"1px solid #d9c391",padding:"1.5rem",display:"grid",gap:"1rem",boxShadow:"0 8px 20px rgba(57,42,25,.08)"},nextCard:{background:"#fff8e8",border:"2px solid #b98b52",padding:"1.2rem 1.4rem",display:"grid",gap:".7rem",boxShadow:"0 8px 20px rgba(57,42,25,.08)"},nextTitle:{fontFamily:"Georgia,serif",fontSize:"1.15rem"},kicker:{textTransform:"uppercase",letterSpacing:".14em",fontSize:11,fontWeight:800,color:"#9b682d"},h1:{fontFamily:"Georgia,serif",fontSize:"clamp(2rem,5vw,3rem)",margin:".35rem 0"},lead:{color:"#725e46",lineHeight:1.65},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:".8rem"},field:{display:"grid",gap:5},input:{border:"1px solid #cdb785",background:"#fffaf0",padding:".75rem",color:"#392a19"},slotGrid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:".6rem"},slot:{border:"1px solid #b99c70",background:"#fffaf0",padding:".75rem",color:"#392a19",cursor:"pointer"},slotOn:{border:"2px solid #7a2e22",background:"rgba(122,46,34,.08)",padding:".7rem",color:"#392a19",fontWeight:800,cursor:"pointer"},primary:{display:"inline-block",width:"fit-content",background:"#7a2e22",color:"#fff8e8",padding:".8rem 1rem",fontWeight:800,textDecoration:"none",cursor:"pointer"},secondary:{display:"inline-block",border:"1px solid #b99c70",color:"#5c3a1e",padding:".8rem 1rem",fontWeight:800,textDecoration:"none"},actions:{display:"flex",flexWrap:"wrap",gap:".7rem"},muted:{color:"#806c52",lineHeight:1.6},error:{border:"1px solid #a64b3b",background:"#fff2ee",padding:".8rem",color:"#7d2e22"}};
