"use client";

import { FormEvent, use, useEffect, useState } from "react";
import OwnPositioningFiles from "@/components/daily/OwnPositioningFiles";
import { positioningSubjectKey, type OwnPositioningSource, type PositioningSubject } from "@/lib/daily/ownPositioning";

type Question={id:string;type:string;label:string;options:string[];required:boolean;help_text?:string};
type Positioning={mode:string;title:string;submitted:boolean;submittedAt?:string|null;status:string;questions:Question[];ownPositioning?:OwnPositioningSource;subject?:PositioningSubject;filledDocumentId?:string|null};

export default function PositioningPage({params}:{params:Promise<{role:string;token:string}>}){
 const{role,token}=use(params);const[data,setData]=useState<Positioning|null>(null);const[answers,setAnswers]=useState<Record<string,string|string[]>>({});const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);const[done,setDone]=useState(false);const[file,setFile]=useState<File|null>(null);const[submissionId]=useState(()=>crypto.randomUUID());
 useEffect(()=>{void(async()=>{const response=await fetch(`/api/daily-portal/${token}/positioning`,{cache:"no-store"});const payload=await response.json().catch(()=>({}));setLoading(false);if(!response.ok)return setError(payload.error??"Positionnement indisponible.");setData(payload.positioning)})()},[token]);
 function setAnswer(question:Question,value:string){setAnswers(current=>({...current,[question.id]:value}))}
 async function submit(event:FormEvent){
  event.preventDefault();setError("");
  if(data?.ownPositioning&&!file)return setError("Joignez le document rempli avant de transmettre votre positionnement.");
  setSubmitting(true);
  try {
   let body:BodyInit=JSON.stringify({answers});
   const headers:Record<string,string>={"Content-Type":"application/json"};
   if(data?.ownPositioning&&file){const form=new FormData();form.set("positioning_source_id",data.ownPositioning.id);form.set("submission_id",submissionId);form.set("positioning_file_0",file);body=form;delete headers["Content-Type"]}
   const response=await fetch(`/api/daily-portal/${token}/positioning`,{method:"POST",headers,body});
   const payload=await response.json().catch(()=>({}));
   if(!response.ok)throw new Error(payload.error??"Transmission impossible.");
   setDone(true);setData(current=>current?{...current,submitted:true,status:payload.status,filledDocumentId:payload.documentId??current.filledDocumentId,questions:[]}:current);
  }catch(cause){setError(cause instanceof Error?cause.message:"Transmission indisponible. Réessayez avec le même document.")}
  finally{setSubmitting(false)}
 }
 return <main style={s.page}><section style={s.hero}><span style={s.kicker}>Selen Daily · Positionnement</span><h1 style={s.title}>{data?.title??"Positionnement avant formation"}</h1><p style={s.text}>Répondez à ces questions avant le début de votre formation. Vos réponses seront rattachées uniquement à votre inscription.</p><a href={`/daily/portail/${role}/${token}`} style={s.back}>← Retour à mon espace</a></section>{loading?<p>Chargement…</p>:null}{error?<p style={s.error}>{error}</p>:null}{data?.mode!=="selen"&&!data?.ownPositioning&&!loading&&!error?<section style={s.card}><h2>Positionnement externe</h2><p style={s.text}>Cette formation utilise un autre mode de positionnement. Les consignes sont disponibles auprès de votre organisme de formation.</p></section>:null}{data?.submitted||done?<section style={s.card}><h2>Positionnement enregistré</h2><p style={s.text}>Votre positionnement a bien été transmis. Aucune nouvelle saisie n’est nécessaire.</p>{data?.filledDocumentId?<a href={`/api/daily-portal/${token}/positioning-document?id=${encodeURIComponent(data.filledDocumentId)}`} download rel="noreferrer">Télécharger mon document rempli</a>:null}</section>:null}{data?.ownPositioning&&data.subject&&!data.submitted&&!done?<form onSubmit={submit} style={s.form}><OwnPositioningFiles downloadUrl={`/api/daily-portal/${token}/positioning-document`} name={data.ownPositioning.name} rows={[{key:positioningSubjectKey(data.subject),subject:data.subject,file:file??undefined}]} onChange={(_key,selected)=>setFile(selected)}/><button type="submit" disabled={submitting||!file} style={s.button}>{submitting?"Transmission…":"Transmettre mon positionnement"}</button></form>:null}{data?.mode==="selen"&&!data.submitted&&!done?<form onSubmit={submit} style={s.form}>{data.questions.map((question,index)=><fieldset key={question.id} style={s.card}><legend style={s.legend}>{index+1}. {question.label}{question.required?" *":""}</legend>{question.help_text?<p style={s.help}>{question.help_text}</p>:null}{question.options?.length?<div style={s.options}>{question.options.map(option=><label key={option} style={s.option}><input type="radio" name={question.id} value={option} checked={answers[question.id]===option} onChange={()=>setAnswer(question,option)} required={question.required}/><span>{option}</span></label>)}</div>:<textarea rows={4} value={typeof answers[question.id]==="string"?answers[question.id] as string:""} onChange={event=>setAnswer(question,event.target.value)} required={question.required} style={s.textarea}/>}</fieldset>)}<button type="submit" disabled={submitting} style={s.button}>{submitting?"Transmission…":"Transmettre mon positionnement"}</button><p style={s.notice}>Une fois transmis, le positionnement est marqué comme réalisé dans le suivi de votre session.</p></form>:null}</main>
}
const s:Record<string,React.CSSProperties>={page:{maxWidth:820,margin:"0 auto",padding:"2rem 1rem 5rem",color:"var(--ink)"},hero:{display:"grid",gap:8,marginBottom:18,padding:18,border:"1px solid var(--sepia-mid)",background:"var(--paper)"},kicker:{fontSize:12,fontWeight:800,color:"var(--rust)",textTransform:"uppercase",letterSpacing:".08em"},title:{margin:0,fontSize:"clamp(1.7rem,4vw,2.4rem)"},text:{margin:0,lineHeight:1.6,color:"var(--ink-soft)"},back:{color:"var(--rust)",fontWeight:800,textDecoration:"none",width:"fit-content"},form:{display:"grid",gap:14},card:{display:"grid",gap:10,padding:18,border:"1px solid var(--sepia-mid)",background:"var(--paper)"},legend:{fontWeight:800,padding:"0 .3rem"},help:{margin:0,color:"var(--ink-soft)",fontSize:14},options:{display:"grid",gap:8},option:{display:"flex",gap:8,alignItems:"flex-start"},textarea:{width:"100%",boxSizing:"border-box",padding:10,border:"1px solid var(--sepia-mid)",background:"var(--paper)",color:"var(--ink)",font:"inherit"},button:{justifySelf:"start",border:0,borderRadius:6,padding:".65rem .85rem",background:"var(--rust)",color:"#fff",fontWeight:800,cursor:"pointer"},notice:{margin:0,color:"var(--ink-soft)",fontSize:13},error:{padding:12,border:"1px solid #a64",background:"#fff4ef",color:"var(--rust)"}};