"use client";
import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import {assistanceFetch} from "@/components/AgentAssistanceBanner";
import LoadingMascot from "@/components/ui/LoadingMascot";
type Session={id:string;internal_reference?:string|null;start_date?:string|null;daily_formations?:{title?:string|null}|null};
type Doc={id:string;document_type:string;status:string;version:number;logical_name:string;metadata?:Record<string,unknown>|null};
const labels:Record<string,string>={training_program:"Programme",training_agreement:"Convention de formation",training_contract:"Contrat de formation professionnelle",convocation:"Convocation",registration_positioning:"Inscription & positionnement",welcome_booklet:"Livret d’accueil",internal_regulations:"Règlement intérieur"};
export default function PretrainingDocumentsPage(){const sp=useSearchParams(),requested=sp.get("session_id")??"";const[sessions,setSessions]=useState<Session[]>([]),[sessionId,setSessionId]=useState(requested),[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
useEffect(()=>{assistanceFetch("/api/client/daily/sessions",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);const rows=(d.sessions??[]).filter((x:any)=>x.status!=="archived");setSessions(rows);setSessionId(cur=>cur||rows[0]?.id||"")}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
useEffect(()=>{if(!sessionId){setDocs([]);return}assistanceFetch(`/api/client/daily/pretraining-documents?session_id=${encodeURIComponent(sessionId)}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setDocs(d.documents??[])}).catch(e=>setError(e.message))},[sessionId]);
const grouped=useMemo(()=>Object.entries(labels).map(([type,label])=>({type,label,rows:docs.filter(d=>d.document_type===type)})),[docs]);
async function generate(){if(!sessionId)return;setBusy(true);setError("");setMessage("");const r=await assistanceFetch("/api/client/daily/pretraining-documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error??"Génération impossible.");else{setDocs(d.documents??[]);setMessage(`${d.count??0} document(s) généré(s). Ils sont transmis au circuit de vérification Studio avant publication.`)}setBusy(false)}
if(loading)return <LoadingMascot message="Sélion prépare les documents avant formation…"/>;
return <main style={{maxWidth:1100,margin:"0 auto",padding:"2rem 1rem 5rem"}}><p style={{fontWeight:800,fontSize:12}}>SELEN DAILY · AVANT</p><h1>Documents avant formation</h1><p>Un seul écran pour préparer le programme, le document contractuel adapté, les convocations, le livret d’accueil, le règlement intérieur et l’inscription/positionnement. Après vérification par Selen, la publication apparaît dans votre tableau de bord et déclenche un seul email.</p>{error?<p style={{padding:12,border:"1px solid #a64b3b"}}>{error}</p>:null}{message?<p style={{padding:12,border:"1px solid #668153"}}>{message}</p>:null}<section style={{display:"flex",gap:12,flexWrap:"wrap",alignItems:"end",margin:"20px 0"}}><label style={{display:"grid",gap:6,fontWeight:700}}>Session<select value={sessionId} onChange={e=>setSessionId(e.target.value)} style={{padding:10,minWidth:300}}><option value="">Choisir une session</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.daily_formations?.title??"Formation"} · {s.internal_reference??s.start_date??s.id.slice(0,8)}</option>)}</select></label><button onClick={()=>void generate()} disabled={!sessionId||busy} style={{padding:"11px 16px",fontWeight:800}}>{busy?"Génération…":"Générer / actualiser les documents"}</button></section><p><strong>Règle contractuelle :</strong> client avec SIRET = convention ; bénéficiaire individuel sans SIRET commanditaire = contrat de formation professionnelle.</p><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:12}}>{grouped.map(g=><article key={g.type} style={{border:"1px solid #d8c7a2",padding:16,background:"#fffaf0"}}><strong>{g.label}</strong>{g.rows.length?g.rows.map(d=><div key={d.id} style={{marginTop:10,fontSize:13}}>v{d.version} · {d.status} · <a href={`/api/client/daily/pretraining-documents/download?id=${encodeURIComponent(d.id)}`} target="_blank" rel="noreferrer">Ouvrir</a>{typeof d.metadata?.learner_name==="string"?<div>{String(d.metadata.learner_name)}</div>:null}</div>):<p style={{fontSize:13,opacity:.7}}>Pas encore généré pour cette session.</p>}</article>)}</section></main>}
