import assert from 'node:assert/strict';
import * as crypto from 'node:crypto';
import { loadTypeScript } from './loadTypeScript.mjs';

export const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const ids={org:uuid(1),user:uuid(2),formation:uuid(3),session:uuid(4),source:uuid(5),submission:uuid(6),learner:uuid(7),enrolment:uuid(8)};
export const blank=Buffer.from('%PDF-1.7\nquestionnaire vierge'),filled=Buffer.from('%PDF-1.7\nquestionnaire rempli par Alice');
export function harness(options={}) {
 const formation={id:ids.formation,user_id:ids.user,organisation_id:ids.org,title:'Formation QA',status:'validated',updated_at:'2026-10-03T21:00:00.000Z',positioning_mode:'off_platform',positioning_questionnaire_document_url:`/api/client/daily/uploads?id=${ids.source}`,public_registration_token:'candidate-token',public_registration_enabled:true};
 const session={id:ids.session,user_id:ids.user,organisation_id:ids.org,formation_id:ids.formation,status:'ready',registration_token:options.legacy?'candidate-token':'session-token',start_date:'2099-01-01',end_date:'2099-01-02',modality:'presentiel',distance_mode:null,schedule_blocks:[],daily_formations:formation};
 const subject={first_name:'Alice',last_name:'Martin',email:'alice@example.test'};
 const learner={id:ids.learner,organisation_id:ids.org,...subject};
 const enrolment={id:ids.enrolment,organisation_id:ids.org,session_id:ids.session,learner_id:ids.learner,status:'pending',positioning_status:'not_started',daily_learners:learner};
 const original={id:ids.source,organisation_id:ids.org,formation_id:null,document_type:'positioning_questionnaire_source',linked_object_type:'organisation',linked_object_id:ids.org,bucket:'documents',storage_path:`daily/${ids.org}/original.pdf`,sha256:crypto.createHash('sha256').update(blank).digest('hex'),mime_type:'application/pdf',status:'to_check',is_current:true,metadata:{original_filename:'Questionnaire.pdf'}};
 const access={id:uuid(9),session_id:ids.session,portal_type:'learner',entity_key:`learner:${ids.learner}`,entity_email:subject.email,status:'sent',expires_at:'2099-01-01T00:00:00Z',metadata:{learner_id:ids.learner,enrolment_id:ids.enrolment},token:'learner-token'};
 const db={daily_formations:[formation],daily_sessions:[session],daily_documents:[original],daily_formation_registration_requests:[],daily_registration_responses:[],daily_onboarding:[{user_id:ids.user,organisation_name:'OF QA'}],daily_portal_access_tokens:[access],daily_session_enrolments:[enrolment],daily_positioning_responses:[],daily_trainer_profiles:[],daily_registration_request_decisions:[],daily_registration_request_enrolments:[],daily_session_checklist_items:[],daily_learning_assessment_responses:[],daily_learning_assessments:[],daily_session_dossiers:[]};
 const storage=new Map([[original.storage_path,blank]]),writes=[],uploads=[],downloads=[],sends=[];
 let user=options.anonymous?null:{id:ids.user,email:subject.email,user_metadata:{}};
 const admin={from(table){
  assert.ok(Object.hasOwn(db,table),`Unexpected table ${table}`);let filters=[],mutation=null,payload,one=false,limit,columns='*';
  const project=row=>row&&columns!=='*'?Object.fromEntries(columns.replace(/\([^)]*\)/g,'').split(',').filter(key=>Object.hasOwn(row,key)).map(key=>[key,row[key]])):row;
  const query={select(value){columns=value;return query;},eq(k,v){filters.push(r=>r[k]===v);return query;},neq(k,v){filters.push(r=>r[k]!==v);return query;},gte(k,v){filters.push(r=>r[k]>=v);return query;},in(k,v){filters.push(r=>v.includes(r[k]));return query;},not(k,op,v){assert.equal(op,'in');filters.push(r=>!v.slice(1,-1).split(',').includes(r[k]));return query;},contains(k,v){filters.push(r=>Object.entries(v).every(([a,b])=>r[k]?.[a]===b));return query;},order(){return query;},limit(n){limit=n;return query;},maybeSingle(){one=true;return query;},single(){one=true;return query;},insert(v){assert.ok(['daily_documents','daily_formation_registration_requests','daily_registration_responses','daily_positioning_responses',...(options.allowFormationWrite?['daily_formations']:[])].includes(table),`Forbidden insert ${table}`);mutation='insert';payload=v;return query;},update(v){assert.ok(['daily_formations','daily_sessions','daily_session_dossiers'].includes(table),`Forbidden update ${table}`);mutation='update';payload=v;return query;},then(resolve,reject){return Promise.resolve().then(()=>{
   if(options.failCurrentSourceRead&&table==='daily_documents'&&columns.includes('linked_object_type')&&columns.includes('sha256')&&!mutation)return{data:null,error:{message:'source read failed'}};
   if(mutation==='insert'){
    if(options.failDocumentWrite&&table==='daily_documents')return{data:null,error:{code:'write_failed'}};
    if(options.failRequestWrite&&table==='daily_formation_registration_requests')return{data:null,error:{code:'write_failed'}};
    if(db[table].some(r=>r.id===payload.id))return{data:null,error:{code:'23505'}};
    const row={id:uuid(100+db[table].length),created_at:'2026-10-02T12:00:00Z',decision_status:'pending',...structuredClone(payload)};db[table].push(row);writes.push({table,row});
    if(table==='daily_documents'&&row.document_type==='positioning_evidence'&&row.enrolment_id===enrolment.id)enrolment.positioning_status='completed';
    if(options.unknownRequestResult&&table==='daily_formation_registration_requests')return{data:null,error:{code:'transport_failed'}};
    return{data:project(row),error:null};
   }
   if(mutation==='update'&&table==='daily_formations')options.beforeFormationUpdate?.(db[table]);
   let rows=db[table].filter(r=>filters.every(f=>f(r)));if(mutation==='update'){rows.forEach(row=>{Object.assign(row,structuredClone(payload));if(table==='daily_formations')row.updated_at=new Date(Date.parse(row.updated_at)+1000).toISOString();});if(rows.length||table!=='daily_formations')writes.push({table,payload});}
   if(limit)rows=rows.slice(0,limit);return{data:one?project(rows[0]??null):rows.map(project),error:null};
  }).then(resolve,reject);}};return query;
 },storage:{from(bucket){assert.equal(bucket,'documents','Only private documents storage is permitted');return{async upload(path,bytes,opts){assert.equal(opts.upsert,false);uploads.push(path);if(options.failUpload)return{error:{message:'mock failure'}};if(storage.has(path))return{error:{message:'already exists'}};storage.set(path,Buffer.from(bytes));return{error:null};},async download(path){downloads.push(path);if(options.failDownload||!storage.has(path))return{data:null,error:{message:'unavailable'}};return{data:new Blob([storage.get(path)]),error:null};}};}}};
 const modules={};
 const paths=new Set(['lib/server/dailyCurrentPositioningEvidence.ts','lib/server/dailySessionCompletion.ts','app/api/client/daily/sessions/completion/route.ts','app/api/client/daily/sessions/[id]/evidence-context/route.ts','lib/daily/ownPositioning.ts','lib/server/dailyOwnPositioning.ts','lib/server/dailyAssessmentSource.ts','lib/server/dailyLearnerOwnPositioning.ts','lib/server/dailyRegistrationPositioning.ts','lib/dailyBeneficiarySiret.ts','lib/dailyRegistration.ts','lib/dailyFormationCreationPolicy.ts','app/api/client/daily/formations/route.ts','app/api/daily-registration/[token]/route.ts','app/api/daily-registration/[token]/positioning-document/route.ts','app/api/daily-portal/[token]/positioning/route.ts','app/api/daily-portal/[token]/positioning-document/route.ts','app/api/client/daily/registration-requests/route.ts']);
 function load(path){
  if(modules[path])return modules[path];assert.ok(paths.has(path),`Unexpected module ${path}`);
  const dependencies={'node:crypto':crypto,crypto,'next/server':{NextResponse:{json:Response.json}},'@/lib/server/clientNdaAccess':{getAdminSupabase:()=>admin},'@/lib/supabase/server':{createClient:async()=>({auth:{getUser:async()=>({data:{user},error:null})}})},'@/lib/server/dailyOrganisationContext':{getDailyOrganisationReadContext:async(_req,capabilities)=>{assert.equal(capabilities.length,1);assert.equal(capabilities[0],'sessions');return options.noSessionAccess?{ok:false,status:403,error:'Forbidden'}:{ok:true,admin,organisationId:ids.org};},getDailyOrganisationContext:async(_req,capability,settings)=>{assert.equal(capability,'trainings');assert.equal(settings.allowAssistanceWrite,true);return options.noFormationAccess?{ok:false,status:403,error:'Forbidden'}:{ok:true,admin,user:{id:ids.user},organisationId:ids.org,assisted:false};}},'@/lib/server/agentAssistance':{logAgentAssistanceAction:async()=>{throw Error('Unexpected assistance mutation');}},'@/lib/server/dailyRegistrationEmails':{sendDailyRegistrationConfirmation:async input=>{sends.push(input);return{sent:true};}},'@/lib/server/dailyClientWorkspace':{getDailyClientWorkspace:async()=>({ok:true,user:{id:ids.user},workspace:{membership:{organisation_id:ids.org,roles:options.nonManager?[]:['manager']}}})},'@/lib/server/dailyLearnerPortalAccess':{sendLearnerPortalAccessForRegistrationRequest:()=>{throw Error('Email forbidden');}},'@/lib/server/dailyEnterprisePortalAccess':{sendEnterprisePortalAccessForRegistrationRequest:()=>{throw Error('Email forbidden');}}};
  for(const candidate of paths)if(candidate.startsWith('lib/')&&candidate!==path)Object.defineProperty(dependencies,'@/'+candidate.slice(0,-3),{get:()=>load(candidate),enumerable:true});
  modules[path]=loadTypeScript(path,dependencies,{Buffer,File,FormData,Response,Request,Headers,Date,crypto:{randomUUID:()=>uuid(1000)},console:{warn(){},error(){}},fetch(){throw Error('Network forbidden');}});return modules[path];
 }
 const body=(extra={})=>({response_type:'beneficiary',respondent_first_name:subject.first_name,respondent_last_name:subject.last_name,respondent_email:subject.email,positioning_source_id:ids.source,submission_id:ids.submission,signature_consent:true,signature_data:'data:image/png;base64,bW9jayBzaWduYXR1cmU=',need_answers:{expectations:'Apprendre'},...extra});
 const multipart=(extra={},files=[new File([filled],'Alice.pdf',{type:'application/pdf'})])=>{const form=new FormData();form.set('payload',JSON.stringify(body(extra)));files.forEach((file,i)=>{if(file)form.set(`positioning_file_${i}`,file);});return form;};
 const params=token=>({params:Promise.resolve({token})});
 const post=async(form=multipart())=>load('app/api/daily-registration/[token]/route.ts').POST(new Request('https://site.test/api/daily-registration/candidate-token',{method:'POST',...(form instanceof FormData?{body:form}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(form)})}),params('candidate-token'));
 return {db,admin,formation,session,subject,learner,enrolment,original,access,storage,writes,uploads,downloads,sends,load,body,multipart,params,post,setUser:value=>user=value};
}
