"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import LoadingMascot from "@/components/ui/LoadingMascot";
import { assistanceFetch } from "@/components/AgentAssistanceBanner";

type Session={id:string;start_date?:string|null;daily_formations?:{title?:string|null}|null;status?:string|null;companies?:Array<Record<string,unknown>>|null};
type Recipient={id:string;kind:"learner"|"company"|"trainer";name:string;detail:string};
const TYPES=[
 ["training_agreement","Convention de formation"],
 ["convocation","Convocation"],
 ["attendance_sheet","Feuille d'émargement"],
 ["completion_certificate","Attestation de fin de formation"],
 ["achievement_certificate","Certificat de réalisation"],
 ["internal_rules","Règlement intérieur"],
 ["welcome_booklet","Livret d'accueil Selen"],
] as const;
const clean=(v:unknown)=>String(v??"").trim();
const kindLabel:Record<Recipient["kind"],string>={learner:"Apprenant",company:"Entreprise",trainer:"Formateur"};
function nameOf(row:Record<string,unknown>,fallback:string){return clean(row.display_name||row.legal_name||row.company_name||row.name||[row.first_name,row.last_name].filter(Boolean).join(" "))||fallback}

export default function DailyManualDocumentVersionsPage(){
 const[sessions,setSessions]=useState<Session[]>([]);const[recipients,setRecipients]=useState<Recipient[]>([]);const[selectedRecipients,setSelectedRecipients]=useState<string[]>([]);const[recipientSearch,setRecipientSearch]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{Promise.all([assistanceFetch("/api/client/daily/sessions",{cache:"no-store"}),assistanceFetch("/api/client/daily/learners",{cache:"no-store"}),assistanceFetch("/api/client/daily/workspace",{cache:"no-store"})]).then(async([sr,lr,wr])=>{const[sb,lb,wb]=await Promise.all([sr.json().catch(()=>({})),lr.json().catch(()=>({})),wr.json().catch(()=>({}))]);if(!sr.ok)throw new Error(sb.error??"Sessions indisponibles.");if(!lr.ok)throw new Error(lb.error??"Apprenants indisponibles.");if(!wr.ok)throw new Error(wb.error??"Formateurs indisponibles.");const active=(sb.sessions??[]).filter((x:Session)=>x.status!=="archived");setSessions(active);const map=new Map<string,Recipient>();for(const row of (lb.learners??[]) as Record<string,unknown>[]){const id=clean(row.id);if(!id)continue;map.set(`learner:${id}`,{id:`learner:${id}`,kind:"learner",name:nameOf(row,"Apprenant"),detail:clean(row.email)||clean(row.company_name)||"Apprenant"})}for(const row of (wb.workspace?.trainers??[]) as Record<string,unknown>[]){const raw=clean(row.id||row.user_id||row.professional_email||row.email);if(!raw)continue;map.set(`trainer:${raw}`,{id:`trainer:${raw}`,kind:"trainer",name:nameOf(row,"Formateur"),detail:clean(row.professional_email||row.email)||"Formateur"})}for(const session of active as Array<Session>){for(const [index,row] of ((session.companies??[]) as Record<string,unknown>[]).entries()){const raw=clean(row.id||row.siret)||`${session.id}-${index}`;map.set(`company:${raw}`,{id:`company:${raw}`,kind:"company",name:nameOf(row,"Entreprise"),detail:clean(row.siret)?`SIRET ${clean(row.siret)}`:"Entreprise / commanditaire"})}}setRecipients([...map.values()].sort((a,b)=>a.name.localeCompare(b.name,"fr")))}).catch(e=>setError(e instanceof Error?e.message:"Chargement impossible.")).finally(()=>setLoading(false))},[]);
 const visibleRecipients=useMemo(()=>{const q=recipientSearch.trim().toLowerCase();return q?recipients.filter(r=>`${r.name} ${r.detail} ${kindLabel[r.kind]}`.toLowerCase().includes(q)):recipients},[recipients,recipientSearch]);
 function toggleRecipient(id:string){setSelectedRecipients(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form),file=fileRef.current?.files?.[0];if(!file){setError("Choisissez le PDF à importer.");return}if(selectedRecipients.length===0){setError("Sélectionnez au moins un apprenant, une entreprise ou un formateur.");return}const selected=recipients.filter(r=>selectedRecipients.includes(r.id));setSaving(true);setError("");setMessage("");let lastVersion:string|number="suivante";for(const recipient of selected){const body=new FormData();body.set("session_id",String(f.get("session_id")??""));body.set("document_type",String(f.get("document_type")??""));body.set("beneficiary",recipient.name);body.set("file",file);const r=await fetch("/api/client/daily/manual-documents",{method:"POST",body});const b=await r.json().catch(()=>({}));if(!r.ok){setError(`${recipient.name} : ${b.error??"Import impossible."}`);setSaving(false);return}lastVersion=b.document?.version??lastVersion}setMessage(`PDF enregistré pour ${selected.length} destinataire${selected.length>1?"s":""}. La version précédente reste conservée dans l'historique.`);setSelectedRecipients([]);setRecipientSearch("");if(fileRef.current)fileRef.current.value="";setSaving(false)}
 if(loading)return <LoadingMascot message="Sélion prépare l'historique documentaire…"/>;
 return <main style={s.page}><section style={s.card}><p style={s.kicker}>Selen Daily · Gestion documentaire</p><h1 style={s.h1}>Importer ou remplacer un PDF</h1><p style={s.text}>Utilisez cet écran lorsqu'un document doit être remplacé par une version signée, corrigée ou personnalisée. Chaque import crée une nouvelle version : l'ancienne reste conservée et n'est jamais écrasée.</p>{error?<p style={s.error}>{error}</p>:null}{message?<p style={s.ok}>{message}</p>:null}<form onSubmit={submit} style={s.form}><label>Session<select name="session_id" required style={s.input}><option value="">Choisir une session</option>{sessions.map(x=><option key={x.id} value={x.id}>{x.daily_formations?.title??"Formation"} · {x.start_date??"date à définir"}</option>)}</select></label><label>Type de document<select name="document_type" required style={s.input}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div style={s.recipientBox}><div style={s.recipientHead}><div><strong>Apprenants, entreprises ou formateurs concernés</strong><p style={s.mini}>{selectedRecipients.length} sélectionné{selectedRecipients.length>1?"s":""}</p></div>{selectedRecipients.length?<button type="button" onClick={()=>setSelectedRecipients([])} style={s.clear}>Tout désélectionner</button>:null}</div><input value={recipientSearch} onChange={e=>setRecipientSearch(e.target.value)} placeholder="Saisir les premières lettres d’un nom…" style={s.input}/><div style={s.recipientList}>{visibleRecipients.length?visibleRecipients.map(r=><label key={r.id} style={s.recipientRow}><input type="checkbox" checked={selectedRecipients.includes(r.id)} onChange={()=>toggleRecipient(r.id)}/><span><strong>{r.name}</strong><small style={s.recipientMeta}>{kindLabel[r.kind]} · {r.detail}</small></span></label>):<p style={s.mini}>Aucun résultat pour cette recherche.</p>}</div></div><label>Nouvelle version PDF<input ref={fileRef} type="file" accept="application/pdf,.pdf" required style={s.input}/></label><button disabled={saving||selectedRecipients.length===0} style={s.button}>{saving?"Import en cours…":"Enregistrer cette nouvelle version"}</button></form><p style={s.note}>PDF uniquement, 10 Mo maximum. La nouvelle version est marquée « à vérifier » afin de conserver le contrôle documentaire avant utilisation définitive.</p></section></main>}
const s:Record<string,React.CSSProperties>={page:{maxWidth:900,margin:"0 auto",padding:"1rem 1rem 5rem",color:"var(--ink)"},card:{border:"1px solid var(--sepia-mid)",background:"var(--paper)",padding:"1.4rem"},kicker:{color:"var(--rust)",fontWeight:800,fontSize:12},h1:{fontFamily:"Georgia,serif",fontSize:"clamp(2rem,5vw,3rem)",margin:".35rem 0"},text:{color:"var(--ink-soft)",lineHeight:1.6},form:{display:"grid",gap:"1rem",marginTop:"1.2rem"},input:{display:"block",width:"100%",boxSizing:"border-box",marginTop:6,padding:10,border:"1px solid var(--sepia-mid)",background:"white"},button:{padding:".8rem 1rem",fontWeight:800,border:"1px solid var(--rust)",background:"var(--rust)",color:"white",cursor:"pointer"},note:{fontSize:13,color:"var(--ink-soft)"},error:{border:"1px solid #a64b3b",background:"#fff2ee",padding:10,color:"#7d2e22"},ok:{border:"1px solid #668153",background:"#f3f8ef",padding:10,color:"#455a3b"},recipientBox:{border:"1px solid var(--sepia-mid)",background:"#fffaf0",padding:"1rem"},recipientHead:{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start",flexWrap:"wrap"},recipientList:{display:"grid",gap:6,maxHeight:300,overflowY:"auto",marginTop:10},recipientRow:{display:"flex",gap:10,alignItems:"flex-start",padding:".65rem",border:"1px solid rgba(160,106,44,.18)",background:"rgba(248,240,220,.55)",cursor:"pointer"},recipientMeta:{display:"block",marginTop:3,color:"var(--ink-soft)"},mini:{margin:".25rem 0",fontSize:13,color:"var(--ink-soft)"},clear:{border:"1px solid var(--sepia-mid)",background:"transparent",padding:".45rem .6rem",color:"var(--rust)",fontWeight:700,cursor:"pointer"}};
