import { NextResponse } from "next/server";
import { getDailyOrganisationContext, getDailyOrganisationReadContext } from "@/lib/server/dailyOrganisationContext";

function text(body:Record<string,unknown>,key:string){return String(body[key]??"").trim()}
export async function GET(req:Request){
 const context=await getDailyOrganisationReadContext(req,["trainings","sessions"]);if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});
 const[learnerR,stakeholderR,feedbackR,actionsR]=await Promise.all([
  context.admin.from("daily_learner_feedback_responses").select("id,session_id,overall_rating,strengths,improvements,free_comment,submitted_at").eq("organisation_id",context.organisationId).order("submitted_at",{ascending:false}).limit(100),
  context.admin.from("daily_stakeholder_satisfaction_responses").select("id,session_id,stakeholder_type,entity_name,overall_rating,strengths,improvements,free_comment,submitted_at").eq("organisation_id",context.organisationId).order("submitted_at",{ascending:false}).limit(100),
  context.admin.from("daily_stakeholder_feedback").select("id,session_id,submission_type,stakeholder_type,submitter_name,subject,message,status,selen_review_note,organisation_response,resolved_at,created_at").eq("organisation_id",context.organisationId).order("created_at",{ascending:false}).limit(100),
  context.admin.from("daily_quality_actions").select("id,session_id,category,source_type,source_id,title,observation,proposed_solution,implemented_improvement,status,implemented_at,created_at,updated_at").eq("organisation_id",context.organisationId).order("created_at",{ascending:false}).limit(150),
 ]);const error=learnerR.error??stakeholderR.error??feedbackR.error??actionsR.error;if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({learnerSatisfaction:learnerR.data??[],stakeholderSatisfaction:stakeholderR.data??[],feedback:feedbackR.data??[],actions:actionsR.data??[]});
}
export async function POST(req:Request){
 const context=await getDailyOrganisationContext(req,"sessions");if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});const body=await req.json().catch(()=>({})) as Record<string,unknown>;const category=text(body,"category"),title=text(body,"title");if(!["incident","difficulty","complaint","corrective_action","improvement"].includes(category)||!title)return NextResponse.json({error:"Catégorie et titre requis."},{status:400});const status=text(body,"status")||"open";if(!["open","planned","implemented","closed"].includes(status))return NextResponse.json({error:"Statut invalide."},{status:400});const now=new Date().toISOString();const{data,error}=await context.admin.from("daily_quality_actions").insert({organisation_id:context.organisationId,session_id:text(body,"session_id")||null,category,title,observation:text(body,"observation")||null,proposed_solution:text(body,"proposed_solution")||null,implemented_improvement:text(body,"implemented_improvement")||null,status,created_by:context.user.id,updated_by:context.user.id,implemented_at:status==="implemented"?now:null}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({action:data},{status:201});
}
export async function PATCH(req:Request){
 const context=await getDailyOrganisationContext(req,"sessions");if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});const body=await req.json().catch(()=>({})) as Record<string,unknown>;const id=text(body,"id"),status=text(body,"status");if(!id||!["open","planned","implemented","closed"].includes(status))return NextResponse.json({error:"Action ou statut invalide."},{status:400});const now=new Date().toISOString();const{data,error}=await context.admin.from("daily_quality_actions").update({status,proposed_solution:text(body,"proposed_solution")||null,implemented_improvement:text(body,"implemented_improvement")||null,updated_by:context.user.id,updated_at:now,implemented_at:status==="implemented"?now:null}).eq("id",id).eq("organisation_id",context.organisationId).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({action:data});
}
