import { NextResponse } from "next/server";
import { getDailyOrganisationContext, getDailyOrganisationReadContext } from "@/lib/server/dailyOrganisationContext";
import { logAgentAssistanceAction } from "@/lib/server/agentAssistance";

function text(body:Record<string,unknown>,key:string){return String(body[key]??"").trim()}
export async function GET(req:Request){
 const context=await getDailyOrganisationReadContext(req,["trainings","sessions"]);if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});
 const url=new URL(req.url);if(url.searchParams.get("scope")==="watch"){const[watchR,usageR,businessR]=await Promise.all([context.admin.from("daily_watch_entries").select("id,watch_type,title,article_url,analysis_and_improvement,published_at").eq("status","active").order("published_at",{ascending:false}),context.admin.from("daily_organisation_watch_entries").select("watch_entry_id,interested,interested_at,improvement_note,forced_by_studio").eq("organisation_id",context.organisationId),context.admin.from("daily_business_watch_entries").select("id,watch_date,title,source_url,improvement_note").eq("organisation_id",context.organisationId).order("watch_date",{ascending:false})]);const watchError=watchR.error??usageR.error??businessR.error;if(watchError)return NextResponse.json({error:watchError.message},{status:500});return NextResponse.json({watch:watchR.data??[],usage:usageR.data??[],business:businessR.data??[]})}

 const[learnerR,stakeholderR,feedbackR,actionsR]=await Promise.all([
  context.admin.from("daily_learner_feedback_responses").select("id,session_id,overall_rating,strengths,improvements,free_comment,submitted_at").eq("organisation_id",context.organisationId).order("submitted_at",{ascending:false}).limit(100),
  context.admin.from("daily_stakeholder_satisfaction_responses").select("id,session_id,stakeholder_type,entity_name,overall_rating,strengths,improvements,free_comment,submitted_at").eq("organisation_id",context.organisationId).order("submitted_at",{ascending:false}).limit(100),
  context.admin.from("daily_stakeholder_feedback").select("id,session_id,submission_type,stakeholder_type,submitter_name,subject,message,status,selen_review_note,organisation_response,resolved_at,created_at").eq("organisation_id",context.organisationId).order("created_at",{ascending:false}).limit(100),
  context.admin.from("daily_quality_actions").select("id,session_id,category,source_type,source_id,title,observation,proposed_solution,implemented_improvement,status,implemented_at,event_date,event_source,responsible_name,corrective_action,corrective_action_date,created_at,updated_at").eq("organisation_id",context.organisationId).order("created_at",{ascending:false}).limit(150),
 ]);const error=learnerR.error??stakeholderR.error??feedbackR.error??actionsR.error;if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({learnerSatisfaction:learnerR.data??[],stakeholderSatisfaction:stakeholderR.data??[],feedback:feedbackR.data??[],actions:actionsR.data??[]});
}
export async function POST(req:Request){
 const context=await getDailyOrganisationContext(req,"sessions",{allowAssistanceWrite:true});if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});
 const body=await req.json().catch(()=>({})) as Record<string,unknown>;const category=text(body,"category"),title=text(body,"title");
 if(!["incident","difficulty","complaint","corrective_action","improvement"].includes(category)||!title)return NextResponse.json({error:"Catégorie et titre requis."},{status:400});
 const status=text(body,"status")||"open";if(!["open","planned","implemented","closed"].includes(status))return NextResponse.json({error:"Statut invalide."},{status:400});
 const isRegister=["incident","difficulty","complaint"].includes(category);const eventDate=text(body,"event_date")||null;if(isRegister&&!eventDate)return NextResponse.json({error:"La date de l’événement est requise."},{status:400});
 const now=new Date().toISOString();const payload={organisation_id:context.organisationId,session_id:text(body,"session_id")||null,category,title,observation:text(body,"observation")||null,proposed_solution:text(body,"proposed_solution")||null,implemented_improvement:text(body,"implemented_improvement")||null,status,created_by:context.user.id,updated_by:context.user.id,implemented_at:status==="implemented"?now:null,event_date:eventDate,event_source:text(body,"event_source")||null,responsible_name:text(body,"responsible_name")||null,corrective_action:text(body,"corrective_action")||null,corrective_action_date:text(body,"corrective_action_date")||null};
 const{data,error}=await context.admin.from("daily_quality_actions").insert(payload).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});
 if(context.assisted&&context.assistance)await logAgentAssistanceAction({supabase:context.admin,req,assistance:context.assistance,action:"daily_quality_register_create",actionLabel:"Création d’une entrée du registre qualité par Studio pour le client",newState:data as Record<string,unknown>});
 return NextResponse.json({action:data},{status:201});
}
export async function PATCH(req:Request){
 const context=await getDailyOrganisationContext(req,"sessions",{allowAssistanceWrite:true});if(!context.ok)return NextResponse.json({error:context.error},{status:context.status});
 const body=await req.json().catch(()=>({})) as Record<string,unknown>;const id=text(body,"id");if(!id)return NextResponse.json({error:"Entrée qualité requise."},{status:400});
 const{data:oldState,error:oldError}=await context.admin.from("daily_quality_actions").select("*").eq("id",id).eq("organisation_id",context.organisationId).maybeSingle();if(oldError)return NextResponse.json({error:oldError.message},{status:500});if(!oldState)return NextResponse.json({error:"Entrée qualité introuvable."},{status:404});
 const category=text(body,"category")||String(oldState.category);if(!["incident","difficulty","complaint","corrective_action","improvement"].includes(category))return NextResponse.json({error:"Qualification invalide."},{status:400});
 const status=text(body,"status")||String(oldState.status);if(!["open","planned","implemented","closed"].includes(status))return NextResponse.json({error:"Statut invalide."},{status:400});
 const title=text(body,"title")||String(oldState.title);const eventDate=text(body,"event_date")||oldState.event_date||null;if(["incident","difficulty","complaint"].includes(category)&&!eventDate)return NextResponse.json({error:"La date de l’événement est requise."},{status:400});
 const now=new Date().toISOString();const updates={category,title,observation:text(body,"observation")||null,proposed_solution:text(body,"proposed_solution")||null,implemented_improvement:text(body,"implemented_improvement")||null,status,event_date:eventDate,event_source:text(body,"event_source")||null,responsible_name:text(body,"responsible_name")||null,corrective_action:text(body,"corrective_action")||null,corrective_action_date:text(body,"corrective_action_date")||null,updated_by:context.user.id,updated_at:now,implemented_at:status==="implemented"?(oldState.implemented_at??now):oldState.implemented_at};
 const{data,error}=await context.admin.from("daily_quality_actions").update(updates).eq("id",id).eq("organisation_id",context.organisationId).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});
 if(context.assisted&&context.assistance)await logAgentAssistanceAction({supabase:context.admin,req,assistance:context.assistance,action:"daily_quality_register_update",actionLabel:"Modification d’une entrée du registre qualité par Studio pour le client",oldState:oldState as Record<string,unknown>,newState:data as Record<string,unknown>});
 return NextResponse.json({action:data});
}
